# Generated by Django 5.1.6 on 2025-03-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='password',
            new_name='vendor_password',
        ),
        migrations.AddField(
            model_name='vendor',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
