# Generated by Django 5.1.6 on 2025-03-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0002_rename_email_vendor_email_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_password',
            new_name='password',
        ),
    ]
