# Generated by Django 5.1.6 on 2025-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0003_rename_email_address_vendor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='has_paid_subscription',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_code',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'M-pesa'), ('PAYPAL', 'PayPal')], default='BANK_TRANSFER', max_length=20),
        ),
    ]
