# Generated by Django 5.1.6 on 2025-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0004_remove_vendor_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='id_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
