# Generated by Django 5.1.6 on 2025-03-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0006_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
