# Generated by Django 5.1.6 on 2025-03-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_gender_item_gender_based_and_more'),
        ('vendorDashboard', '0007_vendor_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='item',
            field=models.ManyToManyField(to='shop.item'),
        ),
    ]
