# Generated by Django 5.1.6 on 2025-03-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_gender_item_gender_based_and_more'),
        ('vendorDashboard', '0008_vendor_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='item',
            field=models.ManyToManyField(related_name='vendors', to='shop.item'),
        ),
    ]
