# Generated by Django 5.1.6 on 2025-03-24 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0010_persistentitemdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentitemdata',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='vendorDashboard.vendor'),
            preserve_default=False,
        ),
    ]
