# Generated by Django 5.1.6 on 2025-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0011_persistentitemdata_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentitemdata',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
