# Generated by Django 5.1.6 on 2025-03-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0012_persistentitemdata_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
    ]
