# Generated by Django 5.1.6 on 2025-03-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0013_vendor_vendor_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
