# Generated by Django 5.1.6 on 2025-03-28 19:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0014_vendor_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='username',
            field=models.CharField(blank=True, default='okoth', max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
