# Generated by Django 5.1.7 on 2025-04-06 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0015_vendor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be exactly 6 characters long and can only contain letters and numbers.', regex='^[a-zA-Z0-9]{6}$')]),
        ),
    ]
