# Generated by Django 5.1.7 on 2025-04-06 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0016_alter_vendor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be exactly 8 characters long, include only letters and numbers, and contain at least one digit.', regex='^(?=.*\\d)[a-zA-Z0-9]{8}$')]),
        ),
    ]
