
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    server {
        # For mapping file extensions to appropriate handling
        include       /etc/nginx/mime.types;
        # To force download of files without MIME mappings for security, so
        # they aren't run in browser
        default_type  application/octet-stream;

        # Set log format
        #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
        #                  '$status $body_bytes_sent "$http_referer" '
        #                  '"$http_user_agent" "$http_x_forwarded_for"';

        #access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;

        # Handling static files
        # Requests to /static/ are served directly from the /static/ directory
        location /static/ {
            alias /static/;
            expires 7d;
        }
        
        # Handling media files (user uploaded)
        #location /media/ {
        #    alias /home/app/web/mediafiles/;
        #}

        #gzip  on;
        location / {
            # Forward requests to Django application
            proxy_pass http://maamaramarket:8000;
            # Pass important headers to Django for proper request handling
            # Original host header
            proxy_set_header Host $host;
            # Client's real IP
            proxy_set_header X-Real-IP $remote_addr;
            # Chain of IP addresses
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # Original protocol
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    include /etc/nginx/conf.d/*.conf;
}

