"""
Django settings for project01 project.
Generated by 'django-admin startproject' using Django 4.2.11.
"""

from pathlib import Path
from datetime import timedelta
import os
import environ
from dotenv import load_dotenv
from celery.schedules import crontab


# =========================================================
# BASE CONFIG
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables (ONLY ONCE)
env = environ.Env()
environ.Env.read_env(BASE_DIR / "project01/.env")
load_dotenv()

# Core Secrets
SECRET_KEY = env("SECRET_KEY")
DEBUG = True

FRONTEND_URL = env("FRONTEND_URL")

# The domains this Django site is allowed to serve. It is specified as a string
# of comma-separated URLs in .env
ALLOWED_HOSTS = env("ALLOWED_HOSTS").strip(",").split(",")

# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    # Channels
    "channels",
    "daphne",

    # Local apps
    "shop",
    "core.apps.CoreConfig",
    "oder",
    "vendorDashboard",
    "ReactSerializers",

    # Third-party apps
    "django_countries",
    "crispy_forms",
    "crispy_bootstrap4",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
]

# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project01.urls"

# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project01.wsgi.application"
ASGI_APPLICATION = "project01.asgi.application"

# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "maamara_db",
        "USER": "maamara_user",
        "PASSWORD": "maamaram@1",
        "HOST": "db",
        "PORT": "5432",
    }
}

# =========================================================
# AUTH
# =========================================================

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/google/success/"
LOGOUT_REDIRECT_URL = "/login/"

# Allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_UNIQUE_EMAIL = True

SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = "ReactSerializers.adapters.MyAdapter"

# Google provider
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKE_ENABLED": True,
        "FETCH_USERINFO": True,
    }
}
SOCIALACCOUNT_STORE_TOKENS = True

# =========================================================
# REST FRAMEWORK + JWT
# =========================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "ReactSerializers.authentication.CookieJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
}

SIMPLE_JWT = {
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# =========================================================
# CORS / CSRF / SESSION
# =========================================================

CORS_ALLOWED_ORIGINS = [FRONTEND_URL]
CSRF_TRUSTED_ORIGINS = [FRONTEND_URL]
CORS_ALLOW_CREDENTIALS = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_NAME = "user_sessionid"

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False

SESSION_ENGINE = "django.contrib.sessions.backends.db"

# =========================================================
# CHANNELS (WEBSOCKETS)
# =========================================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("redis", 6379)]},
    }
}

# =========================================================
# CELERY
# =========================================================

CELERY_BEAT_SCHEDULE = {
    "cleanup_visitor_orders_daily": {
        "task": "oder.task.cleanup_old_visitor_orders",
        "schedule": crontab(hour=2, minute=0),
    },
}

# =========================================================
# STATIC / MEDIA
# =========================================================

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "Admin-Dashboard" / "dist"]
STATIC_ROOT = BASE_DIR / "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Nairobi"
USE_I18N = True
USE_TZ = True

# =========================================================
# CRISPY FORMS
# =========================================================

CRISPY_TEMPLATE_PACK = "bootstrap4"

# =========================================================
# PAYMENT CONFIG
# =========================================================

PAYMENT_GATEWAYS = {
    "mpesa": {
        "consumer_key": env("MPESA_CONSUMER_KEY"),
        "consumer_secret": env("MPESA_CONSUMER_SECRET", default=""),
        "auth_url": env("MPESA_AUTH_URL"),

        "b2c": {
            "initiator_name": env("MPESA_INITIATOR_NAME", default=""),
            "short_code": env("MPESA_SHORT_CODE", default=""),
            "initiator_password": env("MPESA_INITIATOR_PASSWORD", default=""),
            "certificate_path": env("MPESA_CERTIFICATE_PATH", default=""),
            "url": env("MPESA_URL"),

            "result_url": "https://nonvalued-alberta-overexpectantly.ngrok-free.dev/mpesa/result",
            "timeout_url": "https://nonvalued-alberta-overexpectantly.ngrok-free.dev/mpesa/timeout",
        },

        "c2b": {
            "short_code": env("MPESA_C2B_SHORT_CODE", default="600977"),
        },

        "stk_push": {
            "shortcode": env("MPESA_STK_SHORTCODE", default="174379"),
            "passkey": env("MPESA_STK_PASSKEY", default=""),
            "stk_url": env("MPESA_STK_URL"),
            "callback_url": env("MPESA_STK_CALLBACK_URL", default=""),
        },
    },

    "paypal": {
        "base_url": env("PAYPAL_API_BASE"),
        "url": env("PAYPAL_PAYOUT_URL"),
        "auth_url": env("PAYPAL_AUTH_URL"),
        "client_id": env("PAYPAL_CLIENT_ID"),
        "client_secret": env("PAYPAL_CLIENT_SECRET"),
    },

    "kcb": {
        "base_url": env("KCB_API_BASE_URL"),
        "auth_url": env("KCB_OAUTH_URL"),
        "client_id": env("KCB_API_KEY"),
        "client_secret": env("KCB_API_SECRET"),
        "callback_url": env("KCB_CALLBACK_URL"),
    },
}

# =========================================================
# EXTERNAL SERVICES
# =========================================================

EXCHANGE_RATE_API_URL = env("EXCHANGE_RATE_API_URL")

OPENAI_API_KEY = env("OPENAI_API_KEY")
EASYPOST_API_KEY = env("EASYPOST_API_KEY", default="")

EASYPOST_FROM_ADDRESS = {
    "name": env("EASYPOST_FROM_ADDRESS_NAME"),
    "street1": env("EASYPOST_FROM_ADDRESS_STREET"),
    "city": env("EASYPOST_FROM_ADDRESS_CITY"),
    "state": env("EASYPOST_FROM_ADDRESS_STATE"),
    "zip": env("EASYPOST_FROM_ADDRESS_ZIP"),
    "country": env("EASYPOST_FROM_ADDRESS_COUNTRY"),
    "phone": env("EASYPOST_FROM_ADDRESS_PHONE"),
}

# =========================================================
# EMAIL
# =========================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASS")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# =========================================================
# LOGGING
# =========================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"level": "INFO", "class": "logging.StreamHandler"},
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "": {"handlers": ["console"], "level": "INFO"},
    },
}
