"""
Django settings for project01 project.

Generated by 'django-admin startproject' using Django 4.2.11.
"""

from pathlib import Path
import os
from datetime import timedelta
#import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!$om#v2urw9x_3evzp$4r6s2$n)!u+%^^jio17(jl@*u^2!=ty'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1', 'localhost',
    "nonvalued-alberta-overexpectantly.ngrok-free.dev",
    ]

# CORS & CSRF Settings
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
]
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True

# Session & Cookie Settings
# SESSION_COOKIE_AGE = 360   # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False


# settings.py

SESSION_COOKIE_NAME = "user_sessionid"  # For frontend user sessions

# For admin, override in urls.py or middleware, or manually manage:
# Or use default admin session cookie (sessionid)



# Application definition
INSTALLED_APPS = [
    "channels",
    'daphne',
    'shop',
    'core',
    'oder',
    'vendorDashboard',
    'ReactSerializers',
    'django_countries',
    'crispy_forms',
    'crispy_bootstrap4',
    'django.contrib.humanize',
    'rest_framework',
    'rest_framework_simplejwt',
    'user_sessions',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework.authtoken',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project01.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project01.wsgi.application'
ASGI_APPLICATION = "project01.asgi.application"


# REST Framework & JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'ReactSerializers.authentication.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
      
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,  # <-- default items per page
}

from datetime import timedelta

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),  # Match your cookie
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    # Optional:
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

##setup celery 
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "cleanup_visitor_orders_daily": {
        "task": "oder.task.cleanup_old_visitor_orders",
        "schedule": crontab(hour=2, minute=0),  # 2:00 AM daily
    },
}



# #Database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'maamara_db',
        'USER': 'maamara_user',
        'PASSWORD': 'maamaram@1',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = "Africa/Nairobi"
USE_I18N = True
USE_TZ = True

# Static & Media
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR, 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Authentication
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/google/success/'

LOGOUT_REDIRECT_URL = '/login/'

# customize the login adapter
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "none"

ACCOUNT_UNIQUE_EMAIL = True

# allow automatic email linking
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True

# remove safety page
SOCIALACCOUNT_LOGIN_ON_GET = True

# added adapters
SOCIALACCOUNT_ADAPTER = "ReactSerializers.adapters.MyAdapter"

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Stripe
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'your_publishable_key_here')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'your_secret_key_here')

# Mpesa
MPESA_CONSUMER_KEY = "your_consumer_key"
MPESA_CONSUMER_SECRET = "your_consumer_secret"
MPESA_SHORTCODE = "your_shortcode"
MPESA_PASSKEY = "your_passkey"

# PayPal
PAYPAL_RECEIVER_EMAIL = 'sb-vh5hk46533989@business.example.com'
PAYPAL_TEST = True

# Twilio
TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID_REMOVED'
TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN_REMOVED'
TWILIO_PHONE_NUMBER = '+1234567890'

# append slash
APPEND_SLASH = False

# Payment Gateways


import os
import environ

SETTINGS_DIR = os.path.dirname(os.path.abspath(__file__))

env = environ.Env()
env.read_env(os.path.join(SETTINGS_DIR, ".env"))

PAYMENT_GATEWAYS = {
    "mpesa": {
        # Global Auth
        "consumer_key": env("MPESA_CONSUMER_KEY"),
        "consumer_secret": env("MPESA_CONSUMER_SECRET", default=""),
        "auth_url": env(
            "MPESA_AUTH_URL",
            default="https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials",
        ),

        # -----------------
        # B2C CONFIG
        # -----------------
        "b2c": {
            "initiator_name": env("MPESA_INITIATOR_NAME", default=""),
            "short_code": env("MPESA_SHORT_CODE", default=""),
            "security_credential": env("MPESA_SECURITY_CREDENTIAL", default=""),  # DON'T set this here, generate dynamically!
            "url": env("MPESA_URL", default="https://sandbox.safaricom.co.ke/mpesa/b2c/v3/paymentrequest"),
            # "result_url": env("MPESA_RESULT_URL", default="http://127.0.0.1:8000/mpesa/result"),
            # "timeout_url": env("MPESA_TIMEOUT_URL", default="http://127.0.0.1:8000/mpesa/timeout")
            "initiator_password": env("MPESA_INITIATOR_PASSWORD", default="Safaricom123!!"),  # use env here too
            "certificate_path": env("MPESA_CERTIFICATE_PATH", default="/full/path/to/SandboxCertificate.pem"),
            "result_url": "https://nonvalued-alberta-overexpectantly.ngrok-free.dev/mpesa/result",
            "timeout_url": "https://nonvalued-alberta-overexpectantly.ngrok-free.dev/mpesa/timeout",

        },


        # -----------------
        # C2B CONFIG
        # -----------------
        "c2b": {
            "short_code": env("MPESA_C2B_SHORT_CODE", default="600977"),
            "register_url": env("MPESA_C2B_REGISTER_URL", default=""),
            "simulate_url": env("MPESA_C2B_SIMULATE_URL", default=""),
            "confirmation_url": env("MPESA_C2B_CONFIRMATION_URL", default=""),
            "validation_url": env("MPESA_C2B_VALIDATION_URL", default=""),
        },

        # -----------------
        # STK PUSH CONFIG
        # -----------------
        "stk_push": {
            "shortcode": env("MPESA_STK_SHORTCODE", default="174379"),
            "passkey": env("MPESA_STK_PASSKEY", default=""),
            "stk_url": env("MPESA_STK_URL", default="https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"),
            "callback_url": env("MPESA_STK_CALLBACK_URL", default=""),
        },
    },

    # -----------------
    # PAYPAL CONFIG
    # -----------------
    "paypal": {
        "base_url": env("PAYPAL_API_BASE", default="https://api.sandbox.paypal.com"),
        "url": env("PAYPAL_PAYOUT_URL", default="https://api-m.sandbox.paypal.com/v1/payments/payouts"),
        "auth_url": env("PAYPAL_AUTH_URL", default="https://api-m.sandbox.paypal.com/v1/oauth2/token"),
        "client_id": env("PAYPAL_CLIENT_ID", default=""),
        "client_secret": env("PAYPAL_CLIENT_SECRET", default=""),
        "webhook_id": env("WEBHOOK_ID", default="60X768244G056720P"),
        "webhook_id_payout": env("WEBHOOK_ID_PAYOUT", default="82X1678228469634R"),

    },

     # -----------------
    # KCB CONFIG
    # -----------------
    "kcb": {
        "base_url": env("KCB_API_BASE_URL", default="https://api.kcbgroup.com"),
        "auth_url": env("KCB_OAUTH_URL", default="https://accounts.buni.kcbgroup.com/oauth2/token"),
        "client_id": env("KCB_API_KEY", default=""),
        "client_secret": env("KCB_API_SECRET", default=""),
        "callback_url": env("KCB_CALLBACK_URL", default="https://nonvalued-alberta-overexpectantly.ngrok-free.dev/kcb/callback"),
        "grant_types": env("KCB_GRANT_TYPES", default="client_credentials"),
    },


}

# print(PAYMENT_GATEWAYS)

# exchange rate url
EXCHANGE_RATE_API_URL = env("EXCHANGE_RATE_API_URL", default="https://open.er-api.com/v6/latest/USD")


# OPEN AI API
OPENAI_API_KEY = env("OPENAI_API_KEY")

print("this is open ai key", OPENAI_API_KEY)


# EasyPost API Key
EASYPOST_API_KEY = env("EASYPOST_API_KEY", default="")


# Default sender/warehouse address
EASYPOST_FROM_ADDRESS = {
    "name": env("EASYPOST_FROM_ADDRESS_NAME", default="Default Sender"),
    "street1": env("EASYPOST_FROM_ADDRESS_STREET", default="Westlands Road"),
    "city": env("EASYPOST_FROM_ADDRESS_CITY", default="Nairobi"),
    "state": env("EASYPOST_FROM_ADDRESS_STATE", default="Nairobi County"),
    "zip": env("EASYPOST_FROM_ADDRESS_ZIP", default="00800"),
    "country": env("EASYPOST_FROM_ADDRESS_COUNTRY", default="KE"),
    "phone": env("EASYPOST_FROM_ADDRESS_PHONE", default="+254712345678"),
}






# Email
from dotenv import load_dotenv


load_dotenv()

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASS")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


# Social Auth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKE_ENABLED': True,
        'FETCH_USERINFO': True
    }
}
SOCIALACCOUNT_STORE_TOKENS = True

# Channels
# settings.py

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # Redis server settings
        },
    },
}



# Session Engine
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",  # must be INFO or lower
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        # Your custom logger
        "": {  # root logger
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
