# Generated by Django 5.1.6 on 2026-05-22 09:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_vendorrating'),
        ('vendorDashboard', '0015_vendorpayout_paypal_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vendorrating',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorrating',
            name='communication',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vendorrating',
            name='quality',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vendorrating',
            name='shipping',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vendorrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vendorrating',
            constraint=models.UniqueConstraint(fields=('vendor', 'user'), name='unique_vendor_user_rating'),
        ),
        migrations.AddConstraint(
            model_name='vendorrating',
            constraint=models.UniqueConstraint(fields=('vendor', 'visitor_id'), name='unique_vendor_visitor_rating'),
        ),
    ]
