# Generated by Django 5.1.6 on 2026-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_vendorrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
