# Generated by Django 5.1.7 on 2025-10-08 22:47

import django.db.models.deletion
import vendorDashboard.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReactSerializers', '0001_initial'),
        ('oder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('id_number', models.CharField(max_length=12)),
                ('vendor_code', models.CharField(max_length=20, unique=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('address_2', models.CharField(default='', max_length=100)),
                ('product_type', models.CharField(max_length=255)),
                ('is_food', models.CharField(max_length=10)),
                ('Are_You_KEBS_certified', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10, null=True)),
                ('product_description', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=255)),
                ('workshop_location', models.TextField()),
                ('vendor_company_logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'M-pesa'), ('PAYPAL', 'PayPal')], default='BANK_TRANSFER', max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_type', models.CharField(blank=True, choices=[('PHONE', 'Phone Number'), ('TILL', 'Till Number'), ('LIPA_NA_MPESA', 'Paybill')], max_length=20, null=True)),
                ('mpesa_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mpesa_till', models.CharField(blank=True, max_length=20, null=True)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=20, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='vendor_profiles/')),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='ReactSerializers.brand')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='ReactSerializers.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='vendorDashboard.vendor')),
            ],
            options={
                'ordering': ['-date_sold'],
            },
        ),
        migrations.CreateModel(
            name='VendorAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_preference', models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange')], default='refund', max_length=10)),
                ('applied', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oder.oderitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='vendorDashboard.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(choices=[('damaged', 'The Item was delivered broken.'), ('not exact', 'Not the exact Item I expected.'), ('missing', 'The Item is missing.'), ('rejected', "I have changed my mind on keeping the Item, I don't want it anymore!"), ('get something else', 'I want to get something else instead.'), ('broken', ' I broke the item Unknowingly. Can I please get it fixed?'), ('dont want to explain', 'I dont want to explain!')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('approved', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('refund_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_refund', models.BooleanField(default=False)),
                ('customer_preference', models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange')], default='refund', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oder.oderitem')),
                ('vendor_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='vendorDashboard.vendoradjustment')),
            ],
        ),
        migrations.CreateModel(
            name='VendorItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_requests/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('draft_item', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_item_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='vendorDashboard.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_data', models.JSONField()),
                ('item_pdf', models.FileField(blank=True, null=True, upload_to='vendor_items/')),
                ('item_list', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('otp', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout_period_start', models.DateField(default=vendorDashboard.models.default_payout_period_start)),
                ('payout_period_end', models.DateField(default=vendorDashboard.models.default_payout_period_end)),
                ('adjustments', models.ManyToManyField(blank=True, to='vendorDashboard.vendoradjustment')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendorDashboard.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'payout_period_start', 'payout_period_end')},
            },
        ),
    ]
