# Generated by Django 5.1.7 on 2025-10-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='brand_object',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
