# Generated by Django 5.1.7 on 2025-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0003_remove_vendor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='custom_reason',
            field=models.TextField(blank=True, help_text="Used when reason is 'custom'.", null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.TextField(blank=True, choices=[('damaged', 'The item was delivered broken.'), ('not_exact', 'Not the exact item I expected.'), ('missing', 'The item is missing.'), ('rejected', 'I’ve changed my mind — I don’t want it anymore.'), ('get_something_else', 'I want to get something else instead.'), ('broken', 'I broke the item unknowingly. Can it be fixed?'), ('dont_want_to_explain', 'I don’t want to explain!'), ('custom', 'Other (custom reason)')], max_length=100, null=True),
        ),
    ]
