# Generated by Django 5.1.7 on 2025-11-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0004_returnrequest_custom_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
