# Generated by Django 5.1.7 on 2025-11-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0007_alter_returnrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='admin_action',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
