# Generated by Django 5.1.7 on 2025-11-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0008_returnrequest_admin_action_returnrequest_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_refund', 'Approved - Refund'), ('approved_exchange', 'Approved - Exchange'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
