# Generated by Django 5.1.7 on 2025-11-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0009_returnrequest_approved_by_admin_returnrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoradjustment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
