# Generated by Django 5.1.7 on 2025-11-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0012_vendor_bank_account_name_vendor_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayout',
            name='mpesa_conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='mpesa_originator_conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='mpesa_result_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
