# Generated by Django 5.1.7 on 2025-11-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0014_vendorpayout_paypal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayout',
            name='paypal_batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
