# Generated by Django 4.2.11 on 2026-09-21 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0008_alter_category_name'),
        ('vendorDashboard', '0020_vendordraft'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendorpayout',
            name='vp_mpesa_origin_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorpayout',
            name='vp_mpesa_txn_idx',
        ),
        migrations.RenameIndex(
            model_name='returnrequest',
            new_name='vendorDashb_custome_e9a99a_idx',
            old_name='return_customer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='returnrequest',
            new_name='vendorDashb_visitor_084c9b_idx',
            old_name='return_visitor_status_idx',
        ),
        migrations.AddField(
            model_name='solditem',
            name='age_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to='ReactSerializers.agevariant'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to='ReactSerializers.colorvariant'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='size_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to='ReactSerializers.sizestock'),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='mpesa_originator_conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
