# Generated by Django 5.x
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ReactSerializers", "0011_occasion_item_occasions"),
        ("vendorDashboard", "0022_vendorpayout_mpesa_correlation_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemDraft",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(
                    choices=[
                        ("DRAFT", "Draft"),
                        ("SUBMITTED", "Submitted"),
                        ("COMPLETED", "Completed"),
                        ("ABANDONED", "Abandoned"),
                    ],
                    default="DRAFT",
                    max_length=20,
                )),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("created_item", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="source_drafts",
                    to="ReactSerializers.item",
                )),
                ("created_request", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="source_draft_links",
                    to="vendorDashboard.vendoritemrequest",
                )),
                ("owner", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="item_drafts",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("vendor", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="item_drafts",
                    to="vendorDashboard.vendor",
                )),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner", "status", "-updated_at"], name="vendorDashbo_owner_i_8a2c9f_idx"),
                    models.Index(fields=["vendor", "status", "-updated_at"], name="vendorDashbo_vendor__d7e8a8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemDraftMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("media_type", models.CharField(
                    choices=[("image", "Image"), ("video", "Video")],
                    max_length=10,
                )),
                ("kind", models.CharField(
                    choices=[
                        ("main", "Main image"),
                        ("gallery", "Gallery image"),
                        ("variant", "Variant image"),
                        ("video", "Product video"),
                    ],
                    max_length=10,
                )),
                ("slot_key", models.CharField(max_length=120)),
                ("variant_key", models.CharField(blank=True, default="", max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("file", models.FileField(upload_to="item_drafts/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("draft", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="media",
                    to="vendorDashboard.itemdraft",
                )),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draft", "slot_key"),
                        name="unique_item_draft_media_slot",
                    )
                ],
            },
        ),
    ]
