# Generated by Django 4.2.11 on 2026-09-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0024_vendoritemrequest_draft'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itemdraft',
            new_name='vendorDashb_owner_i_1c9364_idx',
            old_name='vendorDashbo_owner_i_8a2c9f_idx',
        ),
        migrations.RenameIndex(
            model_name='itemdraft',
            new_name='vendorDashb_vendor__4cfc23_idx',
            old_name='vendorDashbo_vendor__d7e8a8_idx',
        ),
    ]
