# Generated by Django 5.1.7 on 2025-11-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_voucher_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('vendor_registered', 'Vendor Registered'), ('otp_verified', 'OTP Verified'), ('vendor_approved', 'Vendor Approved'), ('vendor_denied', 'Vendor Denied'), ('login', 'User Logged In'), ('logout', 'User Logged Out'), ('email_sent', 'Email Sent'), ('item_created', 'Item Created'), ('item_updated', 'Item Updated'), ('item_created', 'Item Created'), ('item_sold', 'Item Purchased'), ('item_updated', 'Item Updated'), ('item_updated_qty', 'Item Updated_qty'), ('item_viewed', 'Item Viewed'), ('item_added_to_cart', 'Item Added to Cart'), ('item_removed_from_cart', 'Item Removed from Cart'), ('item_reviewed', 'Item Reviewed'), ('item_shared', 'Item Shared'), ('item_added_to_wishlist', 'Item Added to Wishlist'), ('item_removed_from_wishlist', 'Item Removed from Wishlist'), ('order_created', 'Order Created'), ('order_completed', 'Order Completed'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('exchange_requested', 'Exchange Requested'), ('exchange_approved', 'Exchange Approved')], max_length=50),
        ),
    ]
