# Generated by Django 5.1.7 on 2026-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_visitor_id_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
