# Generated by Django 5.1.6 on 2026-05-19 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 6, 18)),
        ),
    ]
