# Generated by Django 5.1.6 on 2026-06-04 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_voucher_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 7, 4)),
        ),
    ]
