# Generated by Django 5.1.6 on 2026-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_voucher_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
