# Generated by Django 4.2.11 on 2026-09-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_searchevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='core_search_user_id_246ddb_idx',
            old_name='core_search_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='core_search_visitor_feab92_idx',
            old_name='core_search_visitor_created_idx',
        ),
    ]
