# Generated by Django 4.2.11 on 2026-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_core_search_user_created_idx_core_search_user_id_246ddb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('vendor_registered', 'Vendor Registered'), ('otp_verified', 'OTP Verified'), ('vendor_approved', 'Vendor Approved'), ('vendor_denied', 'Vendor Denied'), ('login', 'User Logged In'), ('logout', 'User Logged Out'), ('email_sent', 'Email Sent'), ('item_created', 'Item Created'), ('item_updated', 'Item Updated'), ('item_created', 'Item Created'), ('item_sold', 'Item Purchased'), ('item_updated', 'Item Updated'), ('item_updated_qty', 'Item Updated_qty'), ('item_viewed', 'Item Viewed'), ('item_added_to_cart', 'Item Added to Cart'), ('item_removed_from_cart', 'Item Removed from Cart'), ('item_reviewed', 'Item Reviewed'), ('item_shared', 'Item Shared'), ('item_added_to_wishlist', 'Item Added to Wishlist'), ('item_removed_from_wishlist', 'Item Removed from Wishlist'), ('order_created', 'Order Created'), ('order_completed', 'Order Completed'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('exchange_requested', 'Exchange Requested'), ('exchange_approved', 'Exchange Approved'), ('vendor_item_request_received', 'Vendor Item Request Received'), ('viewed_vendor_requests', 'Vendor Requests Viewed'), ('approved_vendor', 'Vendor Approved'), ('blog_created', 'Blog Created'), ('blog_approved', 'Blog Approved'), ('comment_created', 'Blog Comment Created'), ('react_created', 'Blog Reaction Created'), ('react_removed', 'Blog Reaction Removed'), ('banner_approved', 'Banner Approved'), ('banner_rejected', 'Banner Rejected'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected'), ('return_rejected_vendor', 'Return Rejected'), ('return_rejected_admin', 'Return Rejected'), ('refund_approved_vendor', 'Refund Approved'), ('refund_approved_admin', 'Refund Approved'), ('exchange_approved_vendor', 'Exchange Approved'), ('exchange_approved_admin', 'Exchange Approved'), ('cart_item_removed_notification', 'Item Removed From Cart'), ('paypal_payment', 'PayPal Payment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='actor_type',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('visitor', 'Visitor'), ('guest', 'Guest')], max_length=10),
        ),
    ]
