# Generated by Django 5.1.7 on 2025-10-08 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=30)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('cm', 'Centimeters'), ('m', 'Meters'), ('in', 'Inches')], default='cm', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.FloatField()),
                ('approved', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('organic', 'Organic'), ('departmental', 'Departmental')], max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='ShippingDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='cm', max_length=10)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_type', models.CharField(max_length=100)),
                ('shoe_gender', models.CharField(max_length=50)),
                ('shoe_size', models.JSONField(help_text='Array of sizes: [38, 39, 40]')),
            ],
        ),
        migrations.CreateModel(
            name='SizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.JSONField(blank=True, null=True)),
                ('quantity_in_stock', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('lb', 'Pounds'), ('ml', 'Milliliters'), ('l', 'Liters'), ('oz', 'Ounces')], default='kg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ReactSerializers.department')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='items/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('returnable', models.BooleanField(default=True)),
                ('item_attribute', models.CharField(blank=True, choices=[('handwoven', 'Handwoven'), ('handknitted', 'Handknitted'), ('crocheted', 'Crocheted'), ('embroidered', 'Embroidered'), ('quilted', 'Quilted'), ('tie_dye', 'Tie & Dye'), ('batik', 'Batik'), ('patchwork', 'Patchwork'), ('felted', 'Felted Wool'), ('beaded', 'Beaded'), ('wooden', 'Wooden'), ('stone_carved', 'Stone Carved'), ('clay', 'Clay'), ('ceramic', 'Ceramic'), ('bamboo', 'Bamboo'), ('rattan', 'Rattan/Wicker'), ('leather', 'Leather'), ('recycled', 'Recycled / Upcycled'), ('painted', 'Hand-painted'), ('sculpted', 'Sculpted'), ('engraved', 'Engraved'), ('etched', 'Etched'), ('calligraphy', 'Calligraphy'), ('mosaic', 'Mosaic'), ('wire_wrapped', 'Wire Wrapped'), ('macrame', 'Macrame'), ('resin_cast', 'Resin Cast'), ('glass_blown', 'Glass Blown'), ('pearl_inlay', 'Pearl Inlay'), ('carved', 'Hand-carved'), ('polished', 'Polished'), ('lacquered', 'Lacquered'), ('gilded', 'Gold Leaf / Gilded'), ('homemade', 'Homemade'), ('artisanal', 'Artisanal'), ('fermented', 'Fermented'), ('sun_dried', 'Sun-dried'), ('stone_ground', 'Stone Ground')], max_length=30, null=True)),
                ('gender_based', models.CharField(blank=True, default='none', max_length=15, null=True)),
                ('children_size_based_age', models.CharField(blank=True, default='none', max_length=30, null=True)),
                ('in_offer', models.BooleanField(default=False)),
                ('is_organic', models.BooleanField(default=False)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_fresh_food', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('roast_type', models.CharField(blank=True, choices=[('light', 'Light Roast'), ('medium', 'Medium Roast'), ('dark', 'Dark Roast'), ('espresso', 'Espresso Roast'), ('decaf', 'Decaf')], help_text='Only required if category = Coffee', max_length=50, null=True)),
                ('coffee_state', models.CharField(blank=True, choices=[('whole_beans', 'Whole Beans'), ('ground_coarse', 'Ground – Coarse'), ('ground_medium', 'Ground – Medium'), ('ground_fine', 'Ground – Fine'), ('instant', 'Instant Coffee'), ('capsules', 'Capsules/Pods')], help_text='Only required if category = Coffee', max_length=50, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ReactSerializers.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='ReactSerializers.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='ReactSerializers.department')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
