# Generated by Django 5.1.7 on 2025-10-08 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReactSerializers', '0001_initial'),
        ('vendorDashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendorDashboard.vendor'),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_items', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='agevariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_sizes', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='itemview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='itemview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='length',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='length', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='pricechangerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricechangerequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='pricechangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ReactSerializers.section'),
        ),
        migrations.AddField(
            model_name='department',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='ReactSerializers.section'),
        ),
        migrations.AddField(
            model_name='shippingdimension',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_dimension', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_input', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='sizestock',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_only_icon', to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='sizestock',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='ReactSerializers.colorvariant'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ReactSerializers.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='ReactSerializers.subcategory'),
        ),
        migrations.AddField(
            model_name='weight',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='ReactSerializers.item'),
        ),
        migrations.AlterUniqueTogether(
            name='colorvariant',
            unique_together={('item', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='agevariant',
            unique_together={('item', 'age_group')},
        ),
        migrations.AlterUniqueTogether(
            name='itemview',
            unique_together={('item', 'user', 'visitor_id')},
        ),
        migrations.AddConstraint(
            model_name='sizestock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('variant__isnull', True)), models.Q(('item__isnull', True), ('variant__isnull', False)), _connector='OR'), name='size_stock_attached_to_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='sizestock',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('item', 'size'), name='unique_size_only_variant'),
        ),
        migrations.AddConstraint(
            model_name='sizestock',
            constraint=models.UniqueConstraint(condition=models.Q(('item__isnull', True)), fields=('variant', 'size'), name='unique_size_per_color_variant'),
        ),
    ]
