# Generated by Django 5.1.6 on 2025-03-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0004_remove_order_ordered_remove_order_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderitem',
            name='image',
            field=models.ImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
