# Generated by Django 5.1.6 on 2025-03-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0005_oderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderitem',
            name='image',
        ),
        migrations.AddField(
            model_name='oderitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
