# Generated by Django 5.1.6 on 2025-03-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0006_remove_oderitem_image_oderitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderitem',
            name='image_url',
        ),
    ]
