# Generated by Django 5.1.6 on 2025-03-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0008_billingaddress_order_billing_address_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
