# Generated by Django 5.1.7 on 2025-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0002_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_4_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('PayPal', 'PayPal Payment')], max_length=10),
        ),
    ]
