# Generated by Django 5.1.7 on 2025-11-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0011_alter_transaction_transaction_type'),
        ('vendorDashboard', '0013_vendorpayout_mpesa_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendorDashboard.vendorpayout'),
        ),
    ]
