# Generated by Django 5.1.7 on 2025-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0003_transaction_card_brand_transaction_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('card', 'Card')], default='paypal', max_length=50),
        ),
    ]
