# Generated by Django 5.1.7 on 2025-10-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0006_card_alter_transaction_order_transaction_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='oder.payment'),
        ),
    ]
