# Generated by Django 5.1.7 on 2025-10-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0007_transaction_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
