# Generated by Django 5.1.7 on 2025-10-28 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0008_order_paypal_order_id'),
        ('vendorDashboard', '0003_remove_vendor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='vendorDashboard.vendor'),
        ),
    ]
