# Generated by Django 5.1.7 on 2025-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0010_remove_order_items_oderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('PayPal', 'PayPal Payment'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15),
        ),
    ]
