# Generated by Django 5.1.7 on 2025-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0016_alter_customer_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('vendors', 'Vendors'), ('staffs', 'Staffs'), ('kra', 'KRA Licenses'), ('refund', 'Refund'), ('training', 'Training'), ('subscriptions', 'Subscriptions'), ('rent', 'Rent')], max_length=50, null=True),
        ),
    ]
