# Generated by Django 5.1.7 on 2026-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0017_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
