# Generated by Django 5.1.7 on 2026-02-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0006_remove_item_gender_type'),
        ('oder', '0018_card_visitor_id_transaction_visitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderitem',
            name='age_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReactSerializers.agevariant'),
        ),
        migrations.AddField(
            model_name='oderitem',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReactSerializers.colorvariant'),
        ),
        migrations.AddField(
            model_name='oderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oderitem',
            name='selected_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oderitem',
            name='size_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReactSerializers.sizestock'),
        ),
    ]
