# Generated by Django 5.1.7 on 2026-02-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0019_oderitem_age_variant_oderitem_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderitem',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
