# Generated by Django 5.1.7 on 2026-02-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0020_oderitem_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderitem',
            name='selected_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
