# Generated by Django 4.2.11 on 2026-09-21 02:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0031_invoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='oder_invoic_user_id_37edd5_idx',
            old_name='order_invoi_user_id_4b0b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='oder_invoic_visitor_5a1d9b_idx',
            old_name='order_invoi_visitor__e2b1ab_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='oder_invoic_provide_2a6487_idx',
            old_name='order_invoi_provider_8d93c2_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='oder_order_user_id_ac3b3a_idx',
            old_name='order_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='oder_order_visitor_93bad2_idx',
            old_name='order_visitor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='oder_refund_payment_92dd28_idx',
            old_name='order_refund_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='oder_refund_provide_bc2205_idx',
            old_name='order_refund_provider_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('none', 'No Refund'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='oder.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('PayPal', 'PayPal Payment'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order', 'payment'], name='oder_transa_order_i_894d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='oder_transa_transac_63bd56_idx'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='last_4_digits',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payout',
        ),
    ]
