# Generated by Django 4.2.11 on 2026-09-21 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0021_remove_vendorpayout_vp_mpesa_origin_idx_and_more'),
        ('oder', '0032_rename_order_invoi_user_id_4b0b9c_idx_oder_invoic_user_id_37edd5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendorDashboard.vendorpayout'),
        ),
    ]
