# Generated by Django 4.2.11 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0033_transaction_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
