# Generated by Django 4.2.11 on 2026-09-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0025_rename_vendordashbo_owner_i_8a2c9f_idx_vendordashb_owner_i_1c9364_idx_and_more'),
        ('oder', '0040_remove_card_storage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='card',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Card',
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='checkoutsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='uniq_pending_order_user',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='uniq_pending_order_visitor',
        ),
        migrations.RemoveConstraint(
            model_name='refund',
            name='uniq_refund_provider_reference',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='uniq_c2b_mpesa_receipt',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='uniq_c2b_account_reference',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='uniq_paypal_transaction_vendor',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='uniq_paypal_transaction_no_vendor',
        ),
        migrations.RemoveIndex(
            model_name='checkoutsession',
            name='oder_checkou_user_id_9a4e6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkoutsession',
            name='oder_checkou_visitor_4bb7fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkoutsession',
            name='oder_checkou_expires_0f6f2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='oder_order_user_id_ac3b3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='oder_order_visitor_93bad2_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='oder_transa_order_i_894d9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='oder_transa_transac_63bd56_idx',
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='payment_method',
            field=models.CharField(choices=[('Mpesa', 'M-Pesa'), ('PayPal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='paypal_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('PACKING', 'Packing'), ('READY_TO_SHIP', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('AWAITING_CONFIRMATION', 'Awaiting Customer Confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], default='PENDING_PAYMENT', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('NONE', 'No Return'), ('REQUESTED', 'Return Requested'), ('APPROVED', 'Return Approved'), ('REJECTED', 'Return Rejected'), ('RECEIVED', 'Item Received'), ('REFUNDED', 'Refunded'), ('EXCHANGED', 'Exchanged')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='refund',
            name='provider',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Mpesa', 'M-Pesa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oder.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('PayPal', 'PayPal Payment'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('paypal_transaction_id', 'vendor')},
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__gt', ''), ('provider_reference__isnull', False)), fields=('provider', 'provider_reference'), name='uniq_refund_provider_reference'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
    ]
