# Generated by Django 5.1.7 on 2025-11-07 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='percentage_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage value between 0 and 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
