# Generated by Django 5.1.7 on 2025-11-10 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0003_item_percentage_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage value between 0 and 100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
