# Generated by Django 5.1.7 on 2025-12-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0004_alter_item_percentage_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
