# Generated by Django 5.1.7 on 2025-12-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0005_item_gender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gender_type',
        ),
    ]
