# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReactSerializers", "0008_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_attribute",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
