# Generated by Django 5.1.7 on 2026-09-22
from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def backfill_view_dates_and_dedupe(apps, schema_editor):
    ItemView = apps.get_model("ReactSerializers", "ItemView")
    Item = apps.get_model("ReactSerializers", "Item")

    for view in ItemView.objects.all().iterator():
        viewed_at = view.viewed_at
        view.view_date = (
            timezone.localtime(viewed_at).date()
            if timezone.is_aware(viewed_at)
            else viewed_at.date()
        )
        view.save(update_fields=["view_date"])

    # Keep the first view for each item/viewer/day. This also cleans up
    # anonymous duplicate rows that could exist because SQL NULL values do
    # not make the previous unique_together constraint fully unique.
    duplicate_keys = (
        ItemView.objects
        .values("item_id", "user_id", "visitor_id", "view_date")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )

    for key in duplicate_keys.iterator():
        rows = ItemView.objects.filter(
            item_id=key["item_id"],
            user_id=key["user_id"],
            visitor_id=key["visitor_id"],
            view_date=key["view_date"],
        ).order_by("viewed_at", "id")
        keep_id = rows.values_list("id", flat=True).first()
        if keep_id is not None:
            rows.exclude(id=keep_id).delete()

    # Keep the public counter aligned with the deduplicated view history.
    for item in Item.objects.all().iterator():
        total_views = ItemView.objects.filter(item_id=item.pk).count()
        Item.objects.filter(pk=item.pk).update(views=total_views)


class Migration(migrations.Migration):

    dependencies = [
        ("ReactSerializers", "0011_occasion_item_occasions"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemview",
            name="view_date",
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.RunPython(
            backfill_view_dates_and_dedupe,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="itemview",
            name="view_date",
            field=models.DateField(db_index=True, default=timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name="itemview",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="itemview",
            constraint=models.UniqueConstraint(
                condition=models.Q(user__isnull=False),
                fields=("item", "user", "view_date"),
                name="unique_item_user_day_view",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemview",
            constraint=models.UniqueConstraint(
                condition=models.Q(user__isnull=True, visitor_id__isnull=False),
                fields=("item", "visitor_id", "view_date"),
                name="unique_item_visitor_day_view",
            ),
        ),
    ]
