# Generated by Django 4.2.11 on 2026-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0014_trafficevent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemview',
            name='unique_item_user_lifetime_view',
        ),
        migrations.RemoveConstraint(
            model_name='itemview',
            name='unique_item_visitor_lifetime_view',
        ),
        migrations.RenameIndex(
            model_name='trafficevent',
            new_name='ReactSerial_created_d25458_idx',
            old_name='ReactSerial_created__event_idx',
        ),
        migrations.RenameIndex(
            model_name='trafficevent',
            new_name='ReactSerial_source_e039b6_idx',
            old_name='ReactSerial_source_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trafficevent',
            new_name='ReactSerial_country_a6c9ff_idx',
            old_name='ReactSerial_country_created_idx',
        ),
        migrations.AddConstraint(
            model_name='itemview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('item', 'user'), name='unique_item_user_day_view'),
        ),
        migrations.AddConstraint(
            model_name='itemview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), ('visitor_id__isnull', False)), fields=('item', 'visitor_id'), name='unique_item_visitor_day_view'),
        ),
    ]
