# Generated by Django 5.1.6 on 2025-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_discount_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Home Decor', 'Home Decor'), ('kitchen', 'kitchen'), ('Fashion-men', 'Men Shoe'), ('Fashion-men', 'Men Shirt'), ('Fashion-men', 'Men T-Shirt'), ('Fashion-children', 'Men Hat / cap'), ('Fashion-men', 'Men Trouser'), ('Fashion-women', 'Women Shoe'), ('Fashion-women', 'Women Shirt'), ('Fashion-women', 'Women T-Shirt'), ('Fashion-children', 'Women Hat / cap'), ('Fashion-women', 'Women Trouser'), ('Fashion-children', 'Children Shoe'), ('Fashion-children', 'Children Shirt'), ('Fashion-children', 'Children T-Shirt'), ('Fashion-children', 'Children Trouser'), ('Fashion-children', 'Children Hat / cap'), ('Phone stand', 'Phone stand'), ('Laptop stand', 'Laptop stand'), ('Baskets', 'Baskets'), ('Furnitures', 'Furnitures'), ('Mirror', 'Mirror'), ('Masks', 'Masks'), ('Ornaments', 'Ornaments'), ('Sculptures', 'Sculptures'), ('Kikoi', 'Kikoi'), ('Blankets', 'Blankets'), ('Jewelery', 'Jewelery'), ('Carpet', 'Carpet')], max_length=100, unique=True),
        ),
    ]
