# Generated by Django 5.1.6 on 2025-03-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='children_size_based_age',
            field=models.CharField(blank=True, choices=[(' 0-3 m', ' 0-3 months'), (' 3-6 m', ' 3-6 months '), (' 6-9 m', ' 6-9 months'), (' 9-12 m', ' 9-12 months'), ('12-18 m ', ' 12-18 months'), ('18-24 m ', ' 18-24 months'), ('2 y ', ' 2 years'), ('3 y ', ' 3 years'), ('4 y ', '4 years '), ('6-7 y ', ' 6-7 years'), ('8-10 y ', ' 8-10 years'), ('11-13 y ', ' 11-13 years'), ('14+ y ', ' 14+ years')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('men ', ' For Men'), (' women', ' For women'), (' children', 'For Children '), ('unisex ', ' Unisex')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra-large', 'XL'), ('double-extra-large', 'XXL'), ('triple-extra-large', 'XXXL'), ('free-size', 'Free size'), (' 36', ' 36'), ('37 ', '37 '), (' 38', '38 '), ('39 ', ' 39'), ('40 ', '40 '), ('41 ', ' 41'), (' 42', ' 42'), (' 43', ' 43'), (' 44', ' 44'), (' 45', ' 45'), ('46 ', ' 46'), (' 47', ' 47')], max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
