# Generated by Django 5.1.6 on 2025-03-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_children_size_based_age_item_gender_item_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='gender',
            new_name='gender_based',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra-large', 'XL'), ('double-extra-large', 'XXL'), ('triple-extra-large', 'XXXL'), ('free-size', 'Free size'), (' 36', ' 36'), ('37 ', '37 '), (' 38', '38 '), ('39 ', ' 39'), ('40 ', '40 '), ('41 ', ' 41'), (' 42', ' 42'), (' 43', ' 43'), (' 44', ' 44'), (' 45', ' 45'), ('46 ', ' 46'), (' 47', ' 47')], max_length=30, null=True),
        ),
    ]
