# Generated by Django 5.1.6 on 2025-03-24 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_gender_item_gender_based_and_more'),
        ('vendorDashboard', '0009_alter_vendor_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='persistent_media/')),
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(blank=True, choices=[('Small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra-large', 'XL'), ('double-extra-large', 'XXL'), ('triple-extra-large', 'XXXL'), ('free-size', 'Free size'), (' 36', ' 36'), ('37 ', '37 '), (' 38', '38 '), ('39 ', ' 39'), ('40 ', '40 '), ('41 ', ' 41'), (' 42', ' 42'), (' 43', ' 43'), (' 44', ' 44'), (' 45', ' 45'), ('46 ', ' 46'), (' 47', ' 47')], max_length=30, null=True)),
                ('description', models.TextField()),
                ('gender_based', models.CharField(blank=True, choices=[('men ', ' For Men'), (' women', ' For women'), (' children', 'For Children '), ('unisex ', ' Unisex')], max_length=15, null=True)),
                ('children_size_based_age', models.CharField(blank=True, choices=[(' 0-3 m', ' 0-3 months'), (' 3-6 m', ' 3-6 months '), (' 6-9 m', ' 6-9 months'), (' 9-12 m', ' 9-12 months'), ('12-18 m ', ' 12-18 months'), ('18-24 m ', ' 18-24 months'), ('2 y ', ' 2 years'), ('3 y ', ' 3 years'), ('4 y ', '4 years '), ('6-7 y ', ' 6-7 years'), ('8-10 y ', ' 8-10 years'), ('11-13 y ', ' 11-13 years'), ('14+ y ', ' 14+ years')], max_length=15, null=True)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('in_stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persistent_items', to='shop.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persistent_items', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorDashboard.vendor')),
            ],
        ),
    ]
