# Generated by Django 5.1.6 on 2025-03-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_persistentitemdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersistentItemData',
        ),
    ]
