"""
Django settings for project01 project.
Generated by 'django-admin startproject' using Django 4.2.11.
"""

from pathlib import Path
from datetime import timedelta
import os
import environ
from dotenv import load_dotenv
from celery.schedules import crontab


# =========================================================
# BASE CONFIG
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables (ONLY ONCE)
env = environ.Env()

env_file = BASE_DIR / "project01/.env"
# Check if exists - this fails on docker deployment because the .env is injected via docker compose
if env_file.exists():
    environ.Env.read_env(env_file)

load_dotenv()

# Core Secrets
SECRET_KEY = env("SECRET_KEY")
DEBUG = env.bool("DEBUG", default=False)

FRONTEND_URL = env("FRONTEND_URL")

# Registered PayPal webhook ID. Keep this server-side; it is required to verify
# every PayPal webhook before any payment/refund state is changed.
PAYPAL_WEBHOOK_ID = env("PAYPAL_WEBHOOK_ID", default="")

# The domains this Django site is allowed to serve. It is specified as a string
# of comma-separated URLs in .env
ALLOWED_HOSTS = [host.strip() for host in env("ALLOWED_HOSTS", default="127.0.0.1,localhost").split(",") if host.strip()]

# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    # Channels
    "channels",
    "daphne",

    # Local apps
    "shop",
    "core.apps.CoreConfig",
    "order.apps.OrderConfig",
    "vendorDashboard",
    "ReactSerializers",

    # Third-party apps
    "corsheaders",
    "django_countries",
    "crispy_forms",
    "crispy_bootstrap4",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
]

# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project01.urls"

# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", BASE_DIR / "static"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project01.wsgi.application"
ASGI_APPLICATION = "project01.asgi.application"

# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB", default="maamara_db"),
        "USER": env("POSTGRES_USER", default="maamara_user"),
        "PASSWORD": env("POSTGRES_PASSWORD", default=""),
        "HOST": env("POSTGRES_HOST", default="db"),
        "PORT": env("POSTGRES_PORT", default="5432"),
    }
}

# =========================================================
# AUTH
# =========================================================

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/google/success/"
LOGOUT_REDIRECT_URL = "/login/"

# Allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_UNIQUE_EMAIL = True

SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = "ReactSerializers.adapters.MyAdapter"

# Google provider
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKE_ENABLED": True,
        "FETCH_USERINFO": True,
    }
}
SOCIALACCOUNT_STORE_TOKENS = True

# =========================================================
# REST FRAMEWORK + JWT
# =========================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "ReactSerializers.authentication.CookieJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
}

SIMPLE_JWT = {
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# =========================================================
# CORS / CSRF / SESSION
# =========================================================

CORS_ALLOWED_ORIGINS = [
    origin.strip().rstrip("/")
    for origin in env(
        "CORS_ALLOWED_ORIGINS",
        default=FRONTEND_URL,
    ).split(",")
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip().rstrip("/")
    for origin in env(
        "CSRF_TRUSTED_ORIGINS",
        default=",".join(CORS_ALLOWED_ORIGINS),
    ).split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_NAME = "user_sessionid"

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=FRONTEND_URL.startswith("https://"))
CSRF_COOKIE_HTTPONLY = False

SESSION_ENGINE = "django.contrib.sessions.backends.db"

# =========================================================
# CHANNELS (WEBSOCKETS)
# =========================================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Use explicit Redis connection timeouts. redis-py/channel_redis
            # can otherwise inherit a short socket read timeout, which causes
            # healthy blocking WebSocket reads to fail after several seconds.
            "hosts": [{
                "address": env("REDIS_URL", default="redis://redis:6379/0"),
                "socket_connect_timeout": 5,
                # WebSocket/channel-layer receives are long-lived. A finite
                # socket read timeout can kill an otherwise healthy idle
                # connection with "Timeout reading from redis:6379".
                "socket_timeout": None,
                "retry_on_timeout": True,
            }],
        },
    }
}

# =========================================================
# CELERY
# =========================================================

CELERY_BEAT_SCHEDULE = {
    "cleanup_visitor_orders_daily": {
        "task": "order.task.cleanup_old_visitor_orders",
        "schedule": crontab(hour=2, minute=0),
    },
}

# =========================================================
# STATIC / MEDIA
# =========================================================

STATIC_URL = "/static/"
# The React app is served by Vite in development, not from Django's
# STATICFILES_DIRS. Keeping the frontend dist directory out of this setting
# prevents Django from warning about a directory that does not exist in the
# backend container.
STATIC_ROOT = BASE_DIR / "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Nairobi"
USE_I18N = True
USE_TZ = True

# =========================================================
# CRISPY FORMS
# =========================================================

CRISPY_TEMPLATE_PACK = "bootstrap4"

# =========================================================
# PAYMENT CONFIG
# =========================================================

PAYMENT_GATEWAYS = {
    "mpesa": {
        "consumer_key": env("MPESA_CONSUMER_KEY"),
        "consumer_secret": env("MPESA_CONSUMER_SECRET", default=""),
        "auth_url": env("MPESA_AUTH_URL"),

        "b2c": {
            "initiator_name": env("MPESA_INITIATOR_NAME", default=""),
            "short_code": env("MPESA_SHORT_CODE", default=""),
            "initiator_password": env("MPESA_INITIATOR_PASSWORD", default=""),
            "certificate_path": env("MPESA_CERTIFICATE_PATH", default=""),
            "url": env("MPESA_URL"),

            # Prefer the explicit B2C names, while accepting the legacy
            # names used by existing deployments during the configuration migration.
            "result_url": env(
                "MPESA_B2C_RESULT_URL",
                default=env("MPESA_RESULT_URL", default=""),
            ),
            "timeout_url": env(
                "MPESA_B2C_TIMEOUT_URL",
                default=env("MPESA_TIMEOUT_URL", default=""),
            ),
        },

        "c2b": {
            "short_code": env("MPESA_C2B_SHORT_CODE", default="600977"),
        },

        "reversal": {
            "initiator_name": env("MPESA_REVERSAL_INITIATOR_NAME", default=""),
            "short_code": env("MPESA_REVERSAL_SHORT_CODE", default=""),
            "initiator_password": env("MPESA_REVERSAL_INITIATOR_PASSWORD", default=""),
            "certificate_path": env("MPESA_REVERSAL_CERTIFICATE_PATH", default=""),
            "url": env("MPESA_REVERSAL_URL", default=""),
            "result_url": env("MPESA_REVERSAL_RESULT_URL", default=""),
            "timeout_url": env("MPESA_REVERSAL_TIMEOUT_URL", default=""),
        },

        "stk_push": {
            "shortcode": env("MPESA_STK_SHORTCODE", default="174379"),
            "passkey": env("MPESA_STK_PASSKEY", default=""),
            "stk_url": env("MPESA_STK_URL"),
            "callback_url": env("MPESA_STK_CALLBACK_URL", default=""),
        },
    },

    "paypal": {
        "base_url": env("PAYPAL_API_BASE"),
        "url": env("PAYPAL_PAYOUT_URL"),
        "auth_url": env("PAYPAL_AUTH_URL"),
        "client_id": env("PAYPAL_CLIENT_ID"),
        "client_secret": env("PAYPAL_CLIENT_SECRET"),
        "webhook_id": env("PAYPAL_WEBHOOK_ID", default=""),
    },

    "kcb": {
        "base_url": env("KCB_API_BASE_URL"),
        "auth_url": env("KCB_OAUTH_URL"),
        "client_id": env("KCB_API_KEY"),
        "client_secret": env("KCB_API_SECRET"),
        "callback_url": env("KCB_CALLBACK_URL"),
        "transfer_url": env("KCB_TRANSFER_URL", default=""),
        "status_url": env("KCB_TRANSFER_STATUS_URL", default=""),
        "status_reference_parameter": env("KCB_STATUS_REFERENCE_PARAMETER", default="transactionReference"),
        "company_code": env("KCB_COMPANY_CODE", default=""),
        "debit_account_number": env("KCB_DEBIT_ACCOUNT_NUMBER", default=""),
        "beneficiary_bank_code": env("KCB_BENEFICIARY_BANK_CODE", default=""),
        "transaction_type": env("KCB_TRANSACTION_TYPE", default="IF"),
        "currency": env("KCB_CURRENCY", default="KES"),
        "narrative": env("KCB_TRANSFER_NARRATIVE", default="Automated vendor payment"),
        "beneficiary_details": env("KCB_BENEFICIARY_DETAILS", default="Vendor"),
    },

    "shipping": {
        "dhl": {
            "api_url": env("DHL_RATES_URL", default=""),
            "api_key": env("DHL_API_KEY", default=""),
            "origin_postal_code": env("SHIPPING_ORIGIN_POSTAL_CODE", default="00100"),
            "origin_city": env("SHIPPING_ORIGIN_CITY", default="Nairobi"),
            "origin_country": env("SHIPPING_ORIGIN_COUNTRY", default="KE"),
        },
        "fedex": {
            "auth_url": env("FEDEX_OAUTH_URL", default=""),
            "api_url": env("FEDEX_RATES_URL", default=""),
            "client_id": env("FEDEX_CLIENT_ID", default=""),
            "client_secret": env("FEDEX_CLIENT_SECRET", default=""),
            "account_number": env("FEDEX_ACCOUNT_NUMBER", default=""),
            "origin_postal_code": env("SHIPPING_ORIGIN_POSTAL_CODE", default="00100"),
            "origin_city": env("SHIPPING_ORIGIN_CITY", default="Nairobi"),
            "origin_country": env("SHIPPING_ORIGIN_COUNTRY", default="KE"),
        },
    },
}

# =========================================================
# EXTERNAL SERVICES
# =========================================================

EXCHANGE_RATE_API_URL = env("EXCHANGE_RATE_API_URL")

OPENAI_API_KEY = env("OPENAI_API_KEY")
# =========================================================
# EMAIL
# =========================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASS")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# =========================================================