"""
Django settings for project01 project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!$om#v2urw9x_3evzp$4r6s2$n)!u+%^^jio17(jl@*u^2!=ty'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'core',
    'cart',
    'oder',
    'django_countries',
    'crispy_forms',
    'crispy_forms.templatetags.crispy_forms_field',
    'vendorDashboard',
    'crispy_bootstrap4',
    'django.contrib.humanize',
    'channels',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project01.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'oder.context_processors.cart_item_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'project01.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = 'static/'


STATICFILES_DIRS = [
   BASE_DIR / "static"
]


# settings.py

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'view_cart'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#install crispy forms from bootstrap4

CRISPY_TEMPLATE_PACK = 'bootstrap4'


#deploy stripe for payments
import os

STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'your_publishable_key_here')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'your_secret_key_here')


#mpesa settings
MPESA_CONSUMER_KEY = "your_consumer_key"
MPESA_CONSUMER_SECRET = "your_consumer_secret"
MPESA_SHORTCODE = "your_shortcode"
MPESA_PASSKEY = "your_passkey"

# PayPal settings
# settings.py
PAYPAL_RECEIVER_EMAIL = 'your-paypal-email@example.com'
PAYPAL_TEST = True  # Set to False for live environment

# email logistics and cofig




# Twilio settings for SMS
TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID_REMOVED'
TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN_REMOVED'
TWILIO_PHONE_NUMBER = '+1234567890'  # Your Twilio phone number



PAYMENT_GATEWAYS = {
    'mpesa': {
        'url': 'https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest',
        'auth_url': 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials',
        'consumer_key': 'your_mpesa_consumer_key',
        'consumer_secret': 'your_mpesa_consumer_secret',
        'short_code': 'your_short_code',
        'security_credential': 'your_security_credential',
        'result_url': 'https://yourdomain.com/result',
        'timeout_url': 'https://yourdomain.com/timeout',
    },
    'paypal': {
        'url': 'https://api.sandbox.paypal.com/v1/payments/payouts',
        'auth_url': 'https://api.sandbox.paypal.com/v1/oauth2/token',
        'client_id': 'your_paypal_client_id',
        'client_secret': 'your_paypal_client_secret',
    },
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

ASGI_APPLICATION = 'project01.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


#CORS DELOYMENT

INSTALLED_APPS += ['corsheaders']
MIDDLEWARE += ['corsheaders.middleware.CorsMiddleware']
CORS_ALLOW_ALL_ORIGINS = True  # For development














