from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from rest_framework.pagination import PageNumberPagination
from django.db.models import Min, Max, Count,Prefetch
from ReactSerializers.models import *
from .Serializers import *
from rest_framework import viewsets, permissions
from rest_framework import generics
from .Serializers import BrandSerializer
from ReactSerializers.models import Brand
from rest_framework.views import APIView
from vendorDashboard.models import VendorItemRequest
from vendorDashboard.serializers import VendorItemRequestSerializer
from rest_framework import status
from rest_framework.decorators import action
from .Serializers import BlogPostSerializer
from .models import BlogPost, CareerVacancy, JobApplication, FAQ
from order.views import IsAuthenticatedOrVisitor
from order.models import OrderItem, Order, Customer
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import F
from django.db.models import Avg, Q, Count
from order.Base import IsVendor
from rest_framework.exceptions import PermissionDenied
import uuid
import bleach # type: ignore



class FAQListCreateView(APIView):
    permission_classes = [AllowAny]

    def get(self, request):
        faqs = FAQ.objects.all().values(
            "id", "question", "answer", "category", "created_at", "updated_at"
        )
        data = list(faqs)
        for faq in data:
            faq["answer"] = sanitize_rich_text(faq["answer"] or "")
        return Response(data)

    def post(self, request):
        if not request.user.is_authenticated or not request.user.is_staff:
            return Response({"detail": "Admin access required."}, status=status.HTTP_403_FORBIDDEN)

        question = str(request.data.get("question") or "").strip()
        category = str(request.data.get("category") or "").strip()
        answer = sanitize_rich_text(request.data.get("answer") or "")

        if not question:
            return Response({"question": ["This field is required."]}, status=status.HTTP_400_BAD_REQUEST)

        faq = FAQ.objects.create(question=question[:500], answer=answer, category=category[:120])
        return Response({
            "id": faq.id,
            "question": faq.question,
            "answer": faq.answer,
            "category": faq.category,
            "created_at": faq.created_at,
            "updated_at": faq.updated_at,
        }, status=status.HTTP_201_CREATED)


class FAQDetailView(APIView):
    permission_classes = [AllowAny]

    def patch(self, request, pk):
        if not request.user.is_authenticated or not request.user.is_staff:
            return Response({"detail": "Admin access required."}, status=status.HTTP_403_FORBIDDEN)

        faq = get_object_or_404(FAQ, pk=pk)

        if "question" in request.data:
            faq.question = str(request.data.get("question") or "").strip()[:500]
        if "category" in request.data:
            faq.category = str(request.data.get("category") or "").strip()[:120]
        if "answer" in request.data:
            faq.answer = sanitize_rich_text(request.data.get("answer") or "")

        if not faq.question:
            return Response({"question": ["This field is required."]}, status=status.HTTP_400_BAD_REQUEST)

        faq.save()
        return Response({
            "id": faq.id,
            "question": faq.question,
            "answer": faq.answer,
            "category": faq.category,
            "created_at": faq.created_at,
            "updated_at": faq.updated_at,
        })

    def delete(self, request, pk):
        if not request.user.is_authenticated or not request.user.is_staff:
            return Response({"detail": "Admin access required."}, status=status.HTTP_403_FORBIDDEN)
        faq = get_object_or_404(FAQ, pk=pk)
        faq.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

# -------------------------------
# Sanitizer
# -------------------------------
FAQ_ALLOWED_TAGS = [
    "p", "br", "strong", "b", "em", "i", "u", "s",
    "h2", "h3", "h4", "ul", "ol", "li", "blockquote", "a",
]
FAQ_ALLOWED_ATTRIBUTES = {
    "a": ["href", "title"],
}
FAQ_ALLOWED_PROTOCOLS = ["http", "https", "mailto"]


def sanitize_rich_text(value):
    """Allow only safe formatting generated by the FAQ editor."""
    if not isinstance(value, str):
        return ""
    return bleach.clean(
        value,
        tags=FAQ_ALLOWED_TAGS,
        attributes=FAQ_ALLOWED_ATTRIBUTES,
        protocols=FAQ_ALLOWED_PROTOCOLS,
        strip=True,
    )


def sanitize(value):
    if isinstance(value, str):
        return bleach.clean(value)
    return value


#  chatfile vuew
class FileUploadView(APIView):
    def post(self, request, format=None):
        serializer = ChatFileSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            file_url = request.build_absolute_uri(serializer.data['file'])
            return Response({"fileUrl": file_url, "fileName": request.FILES['file'].name})
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



@api_view(["GET"])
@permission_classes([AllowAny])
def filters_view(request):
    """
    Returns available filters:
      - Sections / Departments / Categories / Subcategories
      - Attributes
      - Genders
      - Sizes
      - Colors
      - Brands
      - Price range
    """

    # Prefetch hierarchy for better performance
    sections = (
        Section.objects.prefetch_related(
            Prefetch(
                "departments",
                queryset=Department.objects.prefetch_related(
                    Prefetch(
                        "categories",
                        queryset=Category.objects.prefetch_related("subcategories")
                    )
                )
            )
        )
    )

    sections_data = SectionSerializer(sections, many=True, context={"request": request}).data

    # ✅ Attributes
    attributes = [attr for attr, _ in Item._meta.get_field("item_attribute").choices]

    # ✅ Genders (excluding "none")
    genders = (
        Item.objects.exclude(gender_based="none")
        .values_list("gender_based", flat=True)
        .distinct()
    )

    # ✅ Sizes (using kids_sizes field instead of non-existent sizes)
    sizes = set()
    for s in Item.objects.values_list("kids_sizes", flat=True):
        if s and isinstance(s, list):
            sizes.update(s)

    # ✅ Colors (if colors is a JSON/Array field on Item — adjust if different)
    colors = set()
    if "colors" in [f.name for f in Item._meta.get_fields()]:
        for c in Item.objects.values_list("colors", flat=True):
            if c and isinstance(c, list):
                colors.update(c)

    # ✅ Brands (from the FK brand)
    brands_qs = (
    Item.objects.filter(brand__isnull=False)
    .values("brand__id", "brand__name")
    .annotate(count=Count("id"))  # Count all items for each brand
    .order_by("brand__name")      # Optional: sort alphabetically
    )

   # Map to frontend-friendly keys
    brands = [
        {
            "id": b["brand__id"],
            "name": b["brand__name"],
            "count": b["count"]
        }
        for b in brands_qs
    ]

    # ✅ Price range
    price_range = Item.objects.aggregate(min=Min("price"), max=Max("price"))

    return Response({
        "sections": sections_data,
        "attributes": attributes,
        "genders": list(genders),
        "sizes": sorted(list(sizes)),
        "colors": sorted(list(colors)),
        "brands": list(brands),
        "priceRange": price_range,
    })


@api_view(["GET"])
@permission_classes([AllowAny])
def products_view(request):
    """
    Unified products API:
    Supports filtering, sorting, and pagination.
    Query params:
      - sections, categories, subcategories, departments, brands (comma-separated IDs)
      - color, gender, attribute, sizes
      - min_price, max_price
      - sortBy (Default | Product Name | Price | Brand)
      - perPage (default=10)
    """
    queryset = Item.objects.filter(in_stock__gt=0, available=True)

    # --- Filtering ---
    if sections := request.GET.get("sections"):
        queryset = queryset.filter(section__id__in=sections.split(","))

    if departments := request.GET.get("departments"):
        queryset = queryset.filter(department__id__in=departments.split(","))

    if categories := request.GET.get("categories"):
        queryset = queryset.filter(category__id__in=categories.split(","))

    if subcategories := request.GET.get("subcategories"):
        queryset = queryset.filter(subcategory__id__in=subcategories.split(","))

    # ✅ Brand filter
    if brands := request.GET.get("brands"):
        queryset = queryset.filter(brand__id__in=brands.split(","))

    # ✅ Color filter
    if color := request.GET.get("color"):
        if "colors" in [f.name for f in Item._meta.get_fields()]:
            queryset = queryset.filter(colors__contains=[color])

    # ✅ Gender filter
    if gender := request.GET.get("gender"):
        queryset = queryset.filter(gender_based__iexact=gender)

    # ✅ Attribute filter
    if attribute := request.GET.get("attribute"):
        queryset = queryset.filter(item_attribute__iexact=attribute)

    # ✅ Size filter (kids_sizes)
    if size := request.GET.get("sizes"):
        queryset = queryset.filter(kids_sizes__contains=[size])

    # ✅ Price filter
    if min_price := request.GET.get("min_price"):
        queryset = queryset.filter(price__gte=min_price)
    if max_price := request.GET.get("max_price"):
        queryset = queryset.filter(price__lte=max_price)

    # --- Sorting ---
    sort_by = request.GET.get("sortBy", "Default")
    if sort_by == "Product Name":
        queryset = queryset.order_by("name")
    elif sort_by == "Price":
        queryset = queryset.order_by("price")
    elif sort_by == "Brand":
        queryset = queryset.order_by("brand__name")
    else:
        queryset = queryset.order_by("-id")  # newest first by default

    # --- Pagination ---
    paginator = PageNumberPagination()
    paginator.page_size = int(request.GET.get("perPage", 10))
    result_page = paginator.paginate_queryset(queryset, request)

    # --- Serialize ---
    serializer = ProductSerializer(result_page, many=True, context={"request": request})
    return paginator.get_paginated_response(serializer.data)





# banner
class BannerViewSet(viewsets.ModelViewSet):
    serializer_class = BannerSerializer
    permission_classes = [permissions.IsAuthenticated, IsVendor]

    def get_queryset(self):
        # Vendors can only see their own banners
        return Banner.objects.filter(
            vendor__user=self.request.user
        )
        
    

# list all banners
class BannerListView(generics.ListAPIView):
    serializer_class = BannerSerializer
    permission_classes = [permissions.AllowAny]

    def get_queryset(self):
        now = timezone.now()

        return Banner.objects.filter(
            is_approved=True,
            is_active=True,
            start_date__lte=now,
        ).filter(
            models.Q(end_date__isnull=True) | models.Q(end_date__gte=now)
        ).order_by("display_order", "-created_at")
    

#Fetch 0nly 4 banners    

    


# fetch barnd serializer
@api_view(["GET"])
@permission_classes([AllowAny])
def list_brands(request):
    brands = Brand.objects.all()
    serializer = BrandSerializer(brands, many=True, context={'request': request})
    return Response(serializer.data)  

 

# show banner details

@api_view(["GET", "PATCH", "PUT", "DELETE"])
@permission_classes([IsAuthenticated])
def banner_detail(request, pk):

    # ================= SAFE LOOKUP (FIX #1) =================
    try:
        banner = Banner.objects.get(pk=pk, vendor=request.user.vendor)
    except Banner.DoesNotExist:
        return Response(
            {"detail": "Banner not found"},
            status=status.HTTP_404_NOT_FOUND
        )

    # ================= GET =================
    if request.method == "GET":
        serializer = BannerSerializer(banner)
        return Response(serializer.data)

    # ================= UPDATE (PATCH / PUT) =================
    if request.method in ["PATCH", "PUT"]:

        data = request.data.copy()

        # ================= CTA SAFETY FIX =================
        # Ensure only one CTA mode is used
        cta_type = data.get("cta_type", banner.cta_type)

        if cta_type == "item":
            data["cta_url"] = None
            # if frontend sends item, map correctly
            if "cta_item" in data and data["cta_item"] == "":
                data["cta_item"] = None

        elif cta_type == "external":
            data["cta_item"] = None

        serializer = BannerSerializer(
            banner,
            data=data,
            partial=(request.method == "PATCH")
        )

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    # ================= DELETE =================
    if request.method == "DELETE":
        banner.delete()
        return Response(
            {"detail": "Banner deleted successfully"},
            status=status.HTTP_204_NO_CONTENT
        )

# vendor blog viewset
class VendorBlogViewSet(viewsets.ModelViewSet):
    serializer_class = BlogPostSerializer
    permission_classes = [permissions.IsAuthenticated]

    # 🔒 Vendor only sees their own blogs
    def get_queryset(self):
        user = self.request.user

        if not hasattr(user, "vendor") or not user.vendor:
            return BlogPost.objects.none()

        return BlogPost.objects.filter(vendor=user.vendor).select_related(
            "user", "vendor"
        )

    # 🔒 Only vendors can create blogs under their account
    def perform_create(self, serializer):
        user = self.request.user

        if not hasattr(user, "vendor") or not user.vendor:
            raise PermissionDenied("Only vendors can create blogs")

        serializer.save(user=user, vendor=user.vendor)

    # 🔒 HARD SECURITY: block access to other vendor blogs
    def get_object(self):
        obj = super().get_object()
        user = self.request.user

        if not hasattr(user, "vendor") or obj.vendor != user.vendor:
            raise PermissionDenied("You can only access your own blogs")

        return obj  
# blog views

from rest_framework import viewsets, status, permissions
from rest_framework.decorators import action
from rest_framework.response import Response


class BlogPostViewSet(viewsets.ModelViewSet):
    serializer_class = BlogPostSerializer
    permission_classes = [permissions.AllowAny]

    def get_queryset(self):
        qs = BlogPost.objects.select_related(
            'user', 'vendor'
        ).prefetch_related(
            'comments_blog', 'reactions_blog'
        )

        # Admins can see everything
        if self.request.user.is_staff and self.request.user.is_superuser:
            return qs

        # Everyone else only sees approved blogs
        return qs.filter(approved=True)

    def perform_create(self, serializer):
        vendor = getattr(self.request.user, "vendor", None)
        blog = serializer.save(user=self.request.user, vendor=vendor)

        # --- Notify all admins ---
        admins = User.objects.filter(is_superuser=True)
        for admin in admins:
            Notification.objects.create(
                user=admin,
                title="New Blog Created",
                message=f"A vendor created the blog {blog.title}.",
                url=f"/admin-dashboard/blogs/{blog.id}/"
            )
            print(f"📢 Admin {admin.username} notified")

        # --- Notify the vendor (optional) ---
        if vendor and vendor.user:
            Notification.objects.create(
                user=vendor.user,
                title="Your Blog Was Created",
                message=f"Your blog {blog.title} has been successfully created.",
                url=f"/vendor/blogs/{blog.id}/"
            )
            print(f"📢 Vendor {vendor.user.username} notified")

        # --- Log activity ---
        ActivityLog.objects.create(
            user=self.request.user,
            actor_type='vendor' if vendor else 'user',
            action="blog_created",
            item=None,  # Not an item, can use blog.id in description
            description=f"You created the blog {blog.title}. The blog is awaiting publication.",
            related_url=f"/blog/{blog.id}/"
        )

        # log admin
        ActivityLog.objects.create(
            user=admin,
            actor_type='admin',
            action="blog_created",
            item=None,  # Not an item, can use blog.id in description
            description=f"A vendor created the blog {blog.title}.",
            related_url=f"/blog/{blog.id}/"
        )
        

    # 💬 POST /api/blogs/{id}/comment/
    @action(detail=True, methods=['post'], permission_classes=[IsAuthenticatedOrVisitor])
    def comment(self, request, pk=None):
        post = self.get_object()
        serializer = CommentSerializer(data=request.data)

        if serializer.is_valid():
            if request.user.is_authenticated:
                comment = serializer.save(post=post, user=request.user)

                # --- Notify the vendor if available ---
                vendor = getattr(post, "vendor", None)
                if vendor and vendor.user:
                    Notification.objects.create(
                        user=vendor.user,
                        title="New Comment on Your Blog",
                        message=f"Your blog {post.title} received a new comment from a customer.",
                        url=f"/vendor/blogs/{post.id}/"
                    )
                    print(f"📢 Vendor {vendor.user.username} notified")

                # --- Log activity for user ---
                ActivityLog.objects.create(
                    user=request.user,
                    actor_type='user',
                    action="comment_created",
                    item=None,
                    description=f"You commented on the blog {post.title}.",
                    related_url=f"/blog/{post.id}/"
                )

                # --- Log activity for admins ---
                admins = User.objects.filter(is_superuser=True)
                for admin in admins:
                    ActivityLog.objects.create(
                        user=admin,
                        actor_type='admin',
                        action="comment_created",
                        item=None,
                        description=f"A customer commented on the blog {post.title}.",
                        related_url=f"/admin-dashboard/blogs/{post.id}/"
                    )
                    print(f"📝 Admin {admin.username} activity logged")
            else:
                # Anonymous comment
                visitor_id = request.COOKIES.get("visitorId")
                serializer.save(post=post, visitor_id=visitor_id, user=None)

            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    # ❤️ POST /api/blogs/{id}/react/
    @action(detail=True, methods=['post'], permission_classes=[IsAuthenticatedOrVisitor])
    def react(self, request, pk=None):
        post = self.get_object()
        reaction_type = request.data.get('type')

        valid_choices = dict(ReactionBlog.REACTION_CHOICES)
        if reaction_type not in valid_choices:
            return Response({"detail": "Invalid reaction type"}, status=status.HTTP_400_BAD_REQUEST)

        if request.user.is_authenticated:
            reaction, created = ReactionBlog.objects.update_or_create(
                post=post,
                user=request.user,
                defaults={'type': reaction_type}
            )

            # --- Notify the vendor if available ---
            vendor = getattr(post, "vendor", None)
            if vendor and vendor.user:
                Notification.objects.create(
                    user=vendor.user,
                    title="New Reaction on Your Blog",
                    message=f"Your blog {post.title} received a {reaction_type} reaction from a customer.",
                    url=f"/vendors-dashboard/vendor/blogs/{post.id}/"
                )
                print(f"📢 Vendor {vendor.user.username} notified")

            # --- Log activity for user ---
            ActivityLog.objects.create(
                user=request.user,
                actor_type='user',
                action="react_created",
                item=None,
                description=f"You reacted with {reaction_type} to the blog {post.title}.",
                related_url=f"/blog/{post.id}/"
            )

            # --- Log activity for admins ---
            admins = User.objects.filter(is_superuser=True)
            for admin in admins:
                ActivityLog.objects.create(
                    user=admin,
                    actor_type='admin',
                    action="react_created",
                    item=None,
                    description=f"A customer reacted with {reaction_type} to the blog {post.title}.",
                    related_url=f"/admin-dashboard/blogs/{post.id}/"
                )
                print(f"📝 Admin {admin.username} activity logged")
        else:
            # Anonymous reaction
            visitor_id = request.COOKIES.get("visitorId")
            reaction, created = ReactionBlog.objects.update_or_create(
                post=post,
                visitor_id=visitor_id,
                defaults={'type': reaction_type}
            )

        return Response(
            ReactionSerializer(reaction).data,
            status=status.HTTP_201_CREATED if created else status.HTTP_200_OK
        )

    # 💔 DELETE /api/blogs/{id}/remove_reaction/
    @action(detail=True, methods=['delete'], permission_classes=[IsAuthenticatedOrVisitor])
    def remove_reaction(self, request, pk=None):
        post = self.get_object()
        if request.user.is_authenticated:
            reaction = ReactionBlog.objects.filter(post=post, user=request.user).first()
        else:
            visitor_id = request.COOKIES.get("visitorId")
            reaction = ReactionBlog.objects.filter(post=post, visitor_id=visitor_id).first()

        if reaction:
            reaction_type = reaction.type
            reaction.delete()

            # --- Notify vendor if available ---
            vendor = getattr(post, "vendor", None)
            if vendor and vendor.user:
                Notification.objects.create(
                    user=vendor.user,
                    title="Reaction Removed from Your Blog",
                    message=f"A {reaction_type} reaction was removed from your blog {post.title}.",
                    url=f"/vendors-dashboard/vendor/blogs/{post.id}/"
                )
                print(f"📢 Vendor {vendor.user.username} notified of removed reaction")

            # --- Log activity for user ---
            if request.user.is_authenticated:
                ActivityLog.objects.create(
                    user=request.user,
                    actor_type='user',
                    action="react_removed",
                    item=None,
                    description=f"You removed your {reaction_type} reaction from the blog {post.title}.",
                    related_url=f"/blog/{post.id}/"
                )

            # --- Log activity for admins ---
            admins = User.objects.filter(is_superuser=True)
            for admin in admins:
                ActivityLog.objects.create(
                    user=admin,
                    actor_type='admin',
                    action="react_removed",
                    item=None,
                    description=f"A customer removed a {reaction_type} reaction from the blog {post.title}.",
                    related_url=f"/admin-dashboard/blogs/{post.id}/"
                )
                print(f"📝 Admin {admin.username} activity logged")

            return Response({"detail": "Reaction removed"}, status=status.HTTP_204_NO_CONTENT)

        return Response({"detail": "No reaction found"}, status=status.HTTP_404_NOT_FOUND)
    


# Admin approve blogs is approved = false
class AdminBlogApprovalViewSet(viewsets.ModelViewSet):
    """
    Fetch blogs that are pending approval for admin review.
    """
    serializer_class = BlogPostSerializer
    permission_classes = [permissions.IsAdminUser]  # Only admins can access

    def get_queryset(self):
        # Only return blogs that are not yet approved
        return BlogPost.objects.filter(approved=False).select_related('user', 'vendor')

    @action(detail=True, methods=['post'])
    def approve(self, request, pk=None):
        blog = self.get_object()
        blog.approved = True
        blog.save()

        # Notify the vendor
        if blog.vendor and blog.vendor.user:
            Notification.objects.create(
                user=blog.vendor.user,
                title="Your blog was approved",
                message=f"Your blog {blog.title} has been approved by the administrator.",
                url=f"/vendors-dashboard/vendor/blogs/{blog.id}/"
            )

        # Log admin activity
        ActivityLog.objects.create(
            user=request.user,
            actor_type='admin',
            action="blog_approved",
            item=None,
            description=f"The administrator approved the blog {blog.title}.",
            related_url=f"/blog/{blog.id}/"
        )

        return Response({
            "detail": f"Blog '{blog.title}' has been approved."
        })    
    
#Admin approve Banner
class AdminBannerApprovalViewSet(viewsets.ModelViewSet):
    """
    Admin: approve/reject banners
    """
    serializer_class = BannerSerializer
    permission_classes = [permissions.IsAdminUser]

    def get_queryset(self):
        return Banner.objects.filter(
            is_approved=False
        ).select_related("vendor", "item").order_by("-created_at")

    # =========================
    # APPROVE
    # =========================
    @action(detail=True, methods=["post"])
    def approve(self, request, pk=None):
        banner = self.get_object()

        banner.is_approved = True
        banner.is_active = True
        banner.approved_at = timezone.now()
        banner.save()

        if banner.vendor and banner.vendor.user:
            Notification.objects.create(
                user=banner.vendor.user,
                title="Banner Approved",
                message=f"Your banner {banner.title} was approved by the administrator.",
                url=f"/vendors-dashboard/vendor/banners/{banner.id}/"
            )

        ActivityLog.objects.create(
            user=request.user,
            actor_type="admin",
            action="banner_approved",
            item=banner.item,
            description=f"The administrator approved the banner {banner.title}.",
            related_url=f"/banners/{banner.id}/"
        )

        return Response({"detail": "Banner approved."}, status=status.HTTP_200_OK)

    # =========================
    # REJECT (CLEAN LIKE BLOG)
    # =========================
    @action(detail=True, methods=["post"])
    def reject(self, request, pk=None):
        banner = self.get_object()
        reason = request.data.get("reason", "")

        title = banner.title

        # 👉 BEST PRACTICE: delete rejected banners
        banner.delete()

        if banner.vendor and banner.vendor.user:
            Notification.objects.create(
                user=banner.vendor.user,
                title="Banner Rejected",
                message=f"Your banner {title} was rejected by the administrator."
                        + (f" Reason: {reason}" if reason else ""),
                url="/vendors-dashboard/vendor/banners/"
            )

        ActivityLog.objects.create(
            user=request.user,
            actor_type="admin",
            action="banner_rejected",
            item=banner.item,
            description=f"The administrator rejected the banner {title}."
                        + (f" Reason: {reason}" if reason else ""),
            related_url="/banners/"
        )

        return Response({"detail": "Banner rejected."}, status=status.HTTP_200_OK)
    

#popular blogs
class PopularBlogPostsViewSet(viewsets.ViewSet):
    """
    Return blogs ordered by total engagement (comments + reactions)
    """
    def list(self, request):
        qs = BlogPost.objects.filter(approved=True).annotate(
            total_comments=Count('comments_blog'),
            total_reactions=Count('reactions_blog'),
        ).order_by('-total_comments', '-total_reactions')[:3]

        serializer = BlogPostSerializer(qs, many=True)
        return Response(serializer.data)
    
#wishlist view add an remove


class WishlistAPIView(APIView):
    permission_classes = [IsAuthenticatedOrVisitor]

    def get_actor(self, request):
        """Identify if it's a user or visitor"""
        if request.user and request.user.is_authenticated:
            return {
                "user": request.user,
                "visitor_id": None,
                "actor_type": "user",
                "actor_name": request.user.username
            }
        else:
            visitor_id = request.COOKIES.get("visitorId")
            if not visitor_id:
                visitor_id = str(uuid.uuid4())
            return {
                "user": None,
                "visitor_id": visitor_id,
                "actor_type": "visitor",
                "actor_name": f"Guest ({visitor_id[:8]})"
            }

    def get(self, request):
        """
        ✅ Get all wishlist items for logged-in user or visitor.
        """
        actor = self.get_actor(request)

        wishlist_items = Wishlist.objects.filter(
            user=actor["user"],
            visitor_id=actor["visitor_id"]
        ).select_related("item")

        # get related Item objects
        items = [w.item for w in wishlist_items]

        serializer = ItemSerializer(items, many=True)

        response = Response({
            "success": True,
            "count": len(items),
            "items": serializer.data
        })

        # ✅ Set visitor cookie if not set yet
        if not request.COOKIES.get("visitorId") and not actor["user"]:
            response.set_cookie(
                "visitorId",
                actor["visitor_id"],
                httponly=True,
                secure=False,
                samesite="Lax",
                max_age=30*24*3600,
            )

        return response

    @transaction.atomic
    def post(self, request, pk):
        """
        Add item to wishlist (user or visitor) and increment item.like only once per actor.
        """
        pk = sanitize(pk)
        item = get_object_or_404(Item, pk=pk)
        actor = self.get_actor(request)

        # --- Prevent duplicate wishlist for same actor ---
        wishlist, created = Wishlist.objects.get_or_create(
            item=item,
            user=actor["user"],
            visitor_id=actor["visitor_id"],
        )

        if created:
            # ✅ Increment item.like atomically
            Item.objects.filter(pk=item.pk).update(likes=F("likes") + 1)
            item.refresh_from_db(fields=['likes'])

            message = "Item added to wishlist"

            # --- One canonical activity event ---
            # The serializer renders "You ..." for the actor and
            # "A customer ..." for other audiences.
            ActivityLog.objects.create(
                user=actor["user"],
                actor_type=actor["actor_type"],
                action="item_added_to_wishlist",
                item=item,
                description=f"A customer added {item.name} to their wishlist.",
                related_url=f"/item/{item.id}/"
            )

            # --- Vendor notification ---
            if item.vendor and item.vendor.user:
                Notification.objects.create(
                    user=item.vendor.user,
                    title="Item added to wishlist",
                    message=f"A customer added {item.name} to their wishlist.",
                    url=f"/item/{item.id}/"
                )

            # --- Admin notifications ---
            superadmins = User.objects.filter(is_superuser=True)
            for admin in superadmins:
                Notification.objects.create(
                    user=admin,
                    title="Item added to wishlist",
                    message=f"A customer added {item.name} to their wishlist.",
                    url=f"/admin-item/vendorDashboard/items/{item.id}/"
                )

        else:
            message = "Item already in wishlist"

        response = Response({
            "success": True,
            "message": message,
            "wishlist_id": wishlist.id,
            "visitor_id": actor["visitor_id"]
        })

        # ✅ Set visitorId cookie if needed
        if not request.COOKIES.get("visitorId") and not actor["user"]:
            response.set_cookie(
                "visitorId",
                actor["visitor_id"],
                httponly=True,
                secure=False,
                samesite="Lax",
                max_age=30*24*3600,
            )

        return response


    @transaction.atomic
    def delete(self, request, pk):
        """
        Remove item from wishlist (user or visitor).
        """
        pk = sanitize(pk)
        item = get_object_or_404(Item, pk=pk)
        actor = self.get_actor(request)

        wishlist_qs = Wishlist.objects.filter(
            item=item,
            user=actor["user"],
            visitor_id=actor["visitor_id"]
        )

        if wishlist_qs.exists():
            wishlist_qs.delete()
            # One canonical activity event for the wishlist change.
            ActivityLog.objects.create(
                user=actor["user"],
                actor_type=actor["actor_type"],
                action="item_removed_from_wishlist",
                item=item,
                description=f"A customer removed {item.name} from their wishlist.",
                related_url=f"/item/{item.id}/"
            )

            # Notifications
            if item.vendor and item.vendor.user:
                Notification.objects.create(
                    user=item.vendor.user,
                    title="Wishlist Update",
                    message=f"A customer removed {item.name} from their wishlist.",
                    url=f"/item/{item.id}/"
                )

            for admin in User.objects.filter(is_superuser=True):
                Notification.objects.create(
                    user=admin,
                    title="Wishlist Update",
                    message=f"A customer removed {item.name} from their wishlist.",
                    url=f"/admin-item/vendorDashboard/items/{item.id}/"
                )

            return Response({"success": True, "message": "Item removed from wishlist"})
        else:
            return Response({"success": False, "message": "Item not found in wishlist"}, status=404)




# -------------------------------
# Single-item marketplace context
# -------------------------------
@api_view(["GET"])
@permission_classes([AllowAny])
def item_marketplace_context(request, pk):
    """
    Lightweight data for the lower sections of the customer product page:
    cart quantity, wishlist saves, related searches, item reviews, shop reviews,
    more from the same shop, and related products.
    """
    item = get_object_or_404(
        Item.objects.select_related(
            "vendor", "category", "subcategory", "department", "section", "brand"
        ),
        pk=pk,
    )

    user = request.user if request.user.is_authenticated else None
    visitor_id = request.COOKIES.get("visitorId")

    wishlist_qs = Wishlist.objects.filter(item=item)
    wishlist_count = wishlist_qs.count()
    if user:
        is_wishlisted = wishlist_qs.filter(user=user).exists()
        cart_qs = OrderItem.objects.filter(
            item=item,
            order__status__iexact="pending",
            order__user=user,
        )
    elif visitor_id:
        is_wishlisted = wishlist_qs.filter(visitor_id=visitor_id).exists()
        cart_qs = OrderItem.objects.filter(
            item=item,
            order__status__iexact="pending",
            order__visitor_id=visitor_id,
        )
    else:
        is_wishlisted = False
        cart_qs = OrderItem.objects.none()

    cart_quantity = cart_qs.aggregate(total=Sum("quantity"))["total"] or 0

    recent_searches = SearchEvent.objects.none()
    if user:
        recent_searches = SearchEvent.objects.filter(
            user=user
        ).order_by("-created_at").values_list("query", flat=True)[:8]
    elif visitor_id:
        recent_searches = SearchEvent.objects.filter(
            visitor_id=visitor_id,
            user__isnull=True,
        ).order_by("-created_at").values_list("query", flat=True)[:8]

    search_terms = []
    seen_terms = set()
    for query in recent_searches:
        normalized = str(query or "").strip()
        key = normalized.lower()
        if normalized and key not in seen_terms:
            seen_terms.add(key)
            search_terms.append(normalized)

    taxonomy_terms = [
        getattr(item.category, "name", None),
        getattr(item.subcategory, "name", None),
        getattr(item.brand, "name", None),
        item.item_attribute,
    ]
    related_searches = []
    for value in taxonomy_terms + search_terms:
        normalized = str(value or "").strip()
        key = normalized.lower()
        if normalized and key not in {x.lower() for x in related_searches}:
            related_searches.append(normalized)
    related_searches = related_searches[:10]

    def compact_product(product):
        image_url = None
        if product.image:
            try:
                image_url = request.build_absolute_uri(product.image.url)
            except Exception:
                image_url = product.image.url

        review_stats = product.reviews.aggregate(
            average=Avg("rating"),
            count=Count("id"),
        )

        return {
            "id": product.id,
            "name": product.name,
            "image": image_url,
            "price": product.price,
            "discount_price": product.discount_price,
            "final_price": round(product.get_item_final_price(), 2),
            "final_discounted_price": round(product.get_item_final_discounted_price(), 2),
            "save_upto": round(product.get_save_upto or 0, 2),
            "percentage_discount": product.percentage_discount,
            "in_stock": product.in_stock,
            "available": product.available,
            "slug": product.slug,
            "likes": product.likes,
            "views": product.views,
            "average_rating": round(review_stats["average"], 2) if review_stats["average"] is not None else None,
            "review_count": review_stats["count"] or 0,
        }

    item_reviews_qs = (
        Review.objects.filter(item=item)
        .select_related("user")
        .prefetch_related("reactions")
        .order_by("-created_at")[:8]
    )
    item_reviews = [
        {
            "id": review.id,
            "user": review.user.username if review.user else "Visitor",
            "rating": review.rating,
            "review_text": review.review_text,
            "created_at": review.created_at,
            "reactions": {
                "like": review.reactions.filter(reaction_type="like").count(),
                "dislike": review.reactions.filter(reaction_type="dislike").count(),
            },
        }
        for review in item_reviews_qs
    ]

    shop_reviews = []
    shop_summary = {
        "rating": 0,
        "review_count": 0,
    }
    if item.vendor:
        vendor_ratings = VendorRating.objects.filter(vendor=item.vendor).select_related("user")
        aggregates = vendor_ratings.aggregate(
            quality=Avg("quality"),
            communication=Avg("communication"),
            shipping=Avg("shipping"),
        )
        rating_values = [
            aggregates["quality"],
            aggregates["communication"],
            aggregates["shipping"],
        ]
        valid_values = [float(value) for value in rating_values if value is not None]
        shop_summary = {
            "rating": round(sum(valid_values) / len(valid_values), 1) if valid_values else 0,
            "review_count": vendor_ratings.count(),
        }
        shop_reviews = [
            {
                "id": review.id,
                "user": review.user.username if review.user else "Visitor",
                "rating": round(
                    (review.quality + review.communication + review.shipping) / 3,
                    1,
                ),
                "comment": review.comment,
                "created_at": review.created_at,
            }
            for review in vendor_ratings.exclude(comment__isnull=True).exclude(comment="").order_by("-created_at")[:8]
        ]

    base_items = Item.objects.filter(
        available=True,
        in_stock__gt=0,
    ).exclude(pk=item.pk).select_related(
        "vendor", "category", "subcategory", "brand"
    )

    more_from_shop_qs = (
        base_items.filter(vendor=item.vendor).order_by("-views", "-likes", "-updated")[:8]
        if item.vendor
        else Item.objects.none()
    )

    related_qs = base_items.filter(
        Q(subcategory=item.subcategory)
        | Q(category=item.category)
        | Q(brand=item.brand)
    ).order_by("-views", "-likes", "-updated")[:8]

    return Response({
        "item": {
            "id": item.id,
            "cart_quantity": int(cart_quantity),
            "wishlist_count": int(wishlist_count),
            "is_wishlisted": is_wishlisted,
            "shop": {
                "id": item.vendor.id if item.vendor else None,
                "name": item.vendor.company_name if item.vendor else None,
                "rating": shop_summary["rating"],
                "review_count": shop_summary["review_count"],
            },
        },
        "related_searches": related_searches,
        "item_reviews": item_reviews,
        "shop_reviews": shop_reviews,
        "shop_summary": shop_summary,
        "more_from_shop": [compact_product(product) for product in more_from_shop_qs],
        "explore_more": [compact_product(product) for product in related_qs],
    })


# vendor ratings
import uuid

class VendorRatingView(APIView):
    permission_classes = [AllowAny]

    def post(self, request, vendor_id):
        try:
            vendor = Vendor.objects.get(id=vendor_id)
        except Vendor.DoesNotExist:
            return Response({"error": "Vendor not found"}, status=404)

        user = request.user if request.user.is_authenticated else None

        # -----------------------
        # AUTHENTICATED USER FLOW
        # -----------------------
        if user:
            rating, created = VendorRating.objects.update_or_create(
                vendor=vendor,
                user=user,
                defaults={
                    "quality": request.data.get("quality", 0),
                    "communication": request.data.get("communication", 0),
                    "shipping": request.data.get("shipping", 0),
                    "comment": request.data.get("comment", "")
                }
            )

        # -----------------------
        # VISITOR FLOW (FIXED)
        # -----------------------
        else:
            visitor_id = request.COOKIES.get("visitor_id")

            if not visitor_id:
                visitor_id = str(uuid.uuid4())

            existing = VendorRating.objects.filter(
                vendor=vendor,
                visitor_id=visitor_id
            ).first()

            if existing:
                return Response(
                    {"error": "You already rated this vendor"},
                    status=400
                )

            rating = VendorRating.objects.create(
                vendor=vendor,
                visitor_id=visitor_id,
                quality=request.data.get("quality", 0),
                communication=request.data.get("communication", 0),
                shipping=request.data.get("shipping", 0),
                comment=request.data.get("comment", "")
            )

        serializer = VendorRatingSerializer(rating)
        response = Response(serializer.data, status=201)

        if not user:
            response.set_cookie(
                "visitor_id",
                visitor_id,
                max_age=60 * 60 * 24 * 365
            )

        return response

    def get(self, request, vendor_id):
        try:
            vendor = Vendor.objects.get(id=vendor_id)
        except Vendor.DoesNotExist:
            return Response({"error": "Vendor not found"}, status=404)

        ratings = VendorRating.objects.filter(vendor=vendor)

        aggregated = ratings.aggregate(
            avg_quality=Avg("quality"),
            avg_communication=Avg("communication"),
            avg_shipping=Avg("shipping"),
        )

        comments = ratings.exclude(comment__isnull=True).exclude(comment="")

        return Response({
            "average_ratings": {
                "quality": round(aggregated["avg_quality"] or 0, 1),
                "communication": round(aggregated["avg_communication"] or 0, 1),
                "shipping": round(aggregated["avg_shipping"] or 0, 1),
            },
            "review_count": ratings.count(),
            "comments": [
                {
                    "user": r.user.username if r.user else "Visitor",
                    "quality": r.quality,
                    "communication": r.communication,
                    "shipping": r.shipping,
                    "comment": r.comment,
                    "created_at": r.created_at,
                }
                for r in comments
            ]
        })
    


# unified vendor review api
class VendorReviewsUnifiedView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        # =========================
        # GET LOGGED-IN VENDOR
        # =========================
        vendor = getattr(request.user, "vendor", None)

        if not vendor:
            return Response(
                {"error": "You are not registered as a vendor"},
                status=403
            )

        # =========================
        # 1. ITEM REVIEWS (ONLY VENDOR ITEMS)
        # =========================
        item_reviews_qs = Review.objects.select_related("item", "user").filter(
            item__vendor=vendor  # 🔥 KEY FILTER
        ).annotate(
            likes=Count("reactions", filter=Q(reactions__reaction_type="like")),
            dislikes=Count("reactions", filter=Q(reactions__reaction_type="dislike")),
            laughs=Count("reactions", filter=Q(reactions__reaction_type="laugh")),
            angries=Count("reactions", filter=Q(reactions__reaction_type="angry")),
        )

        item_reviews = [
            {
                "id": r.id,
                "itemName": r.item.name,
                "user": r.user.username if r.user else "Visitor",
                "rating": r.rating,
                "comment": r.review_text,
                "date": r.created_at,
                "reactions": {
                    "like": r.likes,
                    "dislike": r.dislikes,
                    "laugh": r.laughs,
                    "angry": r.angries,
                }
            }
            for r in item_reviews_qs
        ]

        # =========================
        # 2. VENDOR REVIEWS (ONLY THIS VENDOR)
        # =========================
        vendor_ratings_qs = VendorRating.objects.select_related("user").filter(
            vendor=vendor
        )

        vendor_reviews = [
            {
                "id": r.id,
                "vendorName": vendor.company_name if hasattr(vendor, "company_name") else str(vendor),
                "user": r.user.username if r.user else "Visitor",
                "rating": round((r.quality + r.communication + r.shipping) / 3, 1),
                "comment": r.comment,
                "date": r.created_at,
            }
            for r in vendor_ratings_qs
            if r.comment
        ]

        # =========================
        # 3. VENDOR RATES (SUMMARY)
        # =========================
        vendor_rates = [
            {
                "id": r.id,
                "user": r.user.username if r.user else "Visitor",
                "stars": round((r.quality + r.communication + r.shipping) / 3, 1),
            }
            for r in vendor_ratings_qs
        ]

        # =========================
        # RESPONSE
        # =========================
        return Response({
            "itemReviews": item_reviews,
            "vendorReviews": vendor_reviews,
            "vendorRates": vendor_rates,
        })  
    

#vendor control post review requests    
class VendorBannerViewSet(viewsets.ModelViewSet):
    serializer_class = BannerSerializer
    permission_classes = [permissions.IsAuthenticated, IsVendor]

    def get_queryset(self):
        return Banner.objects.filter(
            vendor=self.request.user.vendor,
            is_active=True
        ).order_by("-created_at")

    def perform_update(self, serializer):
        """
        Update banner WITHOUT changing approval status.
        Approval remains exactly as it was before edit.
        """
        serializer.save()

    def destroy(self, request, *args, **kwargs):
        """
        Soft delete: deactivate banner instead of removing it.
        """
        banner = self.get_object()
        banner.is_active = False
        banner.save()

        return Response(
            {"detail": "Banner deactivated (soft deleted)"},
            status=status.HTTP_200_OK
        )
    

#blog   
class VendorBlogViewSet(viewsets.ModelViewSet):
    serializer_class = BlogPostSerializer
    permission_classes = [permissions.IsAuthenticated, IsVendor]

    def get_queryset(self):
        return BlogPost.objects.filter(
            vendor=self.request.user.vendor
        ).order_by("-created_at")

    def perform_update(self, serializer):
        # ❌ DO NOT reset approval on edit anymore
        serializer.save()

    def destroy(self, request, *args, **kwargs):
        blog = self.get_object()
        blog.delete()

        return Response(
            {"detail": "Blog deleted"},
            status=status.HTTP_200_OK
        )
    

# price history    
class VendorItemRequestViewSet(viewsets.ModelViewSet):
    serializer_class = VendorItemRequestSerializer
    permission_classes = [permissions.IsAuthenticated, IsVendor]

    def get_queryset(self):
        return VendorItemRequest.objects.filter(
            vendor=self.request.user.vendor
        ).order_by("-created_at")

    def perform_update(self, serializer):
        instance = self.get_object()

        if instance.status == "approved":
            raise PermissionDenied("Cannot edit approved request")

        serializer.save()

    def destroy(self, request, *args, **kwargs):
        obj = self.get_object()

        if obj.status == "approved":
            return Response(
                {"detail": "Cannot delete approved request"},
                status=status.HTTP_400_BAD_REQUEST
            )

        obj.delete()
        return Response(
            {"detail": "Deleted"},
            status=status.HTTP_200_OK
        )
    

#Timeline view   
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response


class VendorHistoryTimelineView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        vendor = getattr(request.user, "vendor", None)

        if not vendor:
            return Response([])

        # ======================
        # BANNERS
        # ======================
        banners = Banner.objects.filter(vendor=vendor)

        banner_list = [
            {
                "id": b.id,
                "type": "banners",
                "title": b.title,
                "description": b.subtitle or "",
                "status": "approved" if b.is_approved else "pending",
                "created_at": b.created_at,
            }
            for b in banners
        ]

        # ======================
        # BLOGS
        # ======================
        blogs = BlogPost.objects.filter(vendor=vendor)

        blog_list = [
            {
                "id": b.id,
                "type": "blogs",
                "title": b.title,
                "description": b.content,
                "status": "approved" if b.approved else "pending",
                "created_at": b.created_at,
            }
            for b in blogs
        ]

        # ======================
        # ITEM REQUESTS
        # ======================
        items = VendorItemRequest.objects.filter(vendor=vendor)

        item_list = [
            {
                "id": i.id,
                "type": "prices",
                "title": i.name,
                "description": i.description,
                "status": i.status,
                "created_at": i.created_at,
            }
            for i in items
        ]

        # ======================
        # MERGE + SORT
        # ======================
        timeline = banner_list + blog_list + item_list

        timeline.sort(
            key=lambda x: x["created_at"] or "",
            reverse=True
        )

        return Response(timeline)

# -------------------------------
# Careers
# -------------------------------

@api_view(["GET", "POST"])
def career_vacancies_api(request):
    if request.method == "GET":
        vacancies = CareerVacancy.objects.all() if request.user.is_staff else CareerVacancy.objects.filter(is_active=True)
        return Response(CareerVacancySerializer(vacancies, many=True).data)

    if not request.user.is_authenticated or not request.user.is_staff:
        return Response({"detail": "Admin access required."}, status=status.HTTP_403_FORBIDDEN)

    serializer = CareerVacancySerializer(data=request.data)
    if serializer.is_valid():
        return Response(serializer.data if serializer.save() else serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(["GET"])
def job_vacancy_detail_api(request, pk):
    vacancy = get_object_or_404(CareerVacancy, pk=pk, is_active=True)
    return Response(CareerVacancySerializer(vacancy).data)


@api_view(["PUT", "PATCH", "DELETE"])
@permission_classes([permissions.IsAdminUser])
def career_vacancy_detail_api(request, pk):
    vacancy = get_object_or_404(CareerVacancy, pk=pk)

    if request.method == "DELETE":
        vacancy.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    serializer = CareerVacancySerializer(vacancy, data=request.data, partial=request.method == "PATCH")
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(["POST"])
@permission_classes([IsAuthenticatedOrVisitor])
def apply_for_job_api(request):
    serializer = JobApplicationSerializer(data=request.data)
    if serializer.is_valid():
        application = serializer.save(seen=False)
        return Response(JobApplicationSerializer(application).data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(["PATCH"])
@permission_classes([permissions.IsAdminUser])
def mark_application_seen(request, pk):
    application = get_object_or_404(JobApplication, pk=pk)
    application.seen = True
    application.save(update_fields=["seen"])
    return Response({"message": "Marked as seen"})


@api_view(["GET"])
@permission_classes([permissions.IsAdminUser])
def get_job_applications_api(request):
    applications = JobApplication.objects.select_related("vacancy").all()
    return Response(JobApplicationSerializer(applications, many=True).data)


@api_view(["GET"])
@permission_classes([permissions.IsAdminUser])
def unseen_applications_count_api(request):
    return Response({"unseen": JobApplication.objects.filter(seen=False).count()})


@api_view(["GET"])
def career_stats_api(request):
    User = get_user_model()
    stats = {
        "total_vacancies": CareerVacancy.objects.count(),
        "active_vacancies": CareerVacancy.objects.filter(is_active=True).count(),
        "vendors_supported": Vendor.objects.count(),
        "customers_reached": Customer.objects.count(),
        "team_members": User.objects.filter(is_staff=True).count(),
        "region": "East Africa",
    }
    return Response(stats)