# Generated by Django 5.1.7 on 2025-10-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0004_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('PayPal', 'PayPal'), ('card', 'Card')], default='Mpesa', max_length=20),
        ),
    ]
