# Generated by Django 5.1.7 on 2025-11-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0012_transaction_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_invoice_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
