# Generated by Django 5.1.7 on 2025-11-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0013_order_paypal_invoice_id'),
        ('vendorDashboard', '0015_vendorpayout_paypal_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('paypal_transaction_id', 'vendor')},
        ),
    ]
