# Generated by Django 5.1.7 on 2025-10-12 22:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0002_initial'),
        ('shop', '0001_initial'),
        ('vendorDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner headline', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Optional tagline', max_length=500, null=True)),
                ('image', models.ImageField(help_text='Upload a banner image (recommended 16:9 ratio)', upload_to='banners/')),
                ('call_to_action_url', models.URLField(blank=True, help_text='Optional link to product or page', null=True)),
                ('background_color', models.CharField(blank=True, help_text='Hex or Tailwind color', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='ReactSerializers.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='vendorDashboard.vendor')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
