# Generated by Django 5.1.7 on 2025-10-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_hash',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
