# Generated by Django 5.1.7 on 2025-10-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_banner_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a banner image (recommended 16:9 ratio)', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, null=True, unique=True),
        ),
    ]
