# Generated by Django 5.1.7 on 2025-10-17 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_reaction_options_reaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentBlog',
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'Reaction', 'verbose_name_plural': 'Reactions'},
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('laugh', 'Laugh'), ('angry', 'Angry')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='review',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='shop.review'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='type',
        ),
        migrations.CreateModel(
            name='ReactionBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('fire', '🔥 Fire')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='shop.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
