# Generated by Django 5.1.7 on 2025-10-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_comment_commentblog_alter_reaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblog',
            name='post',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_blog', to='shop.blogpost'),
        ),
        migrations.AlterField(
            model_name='reactionblog',
            name='post',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions_blog', to='shop.blogpost'),
        ),
    ]
