# Generated by Django 5.1.7 on 2025-10-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_commentblog_post_alter_reactionblog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
