# Generated by Django 5.1.6 on 2026-06-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactSerializers', '0008_alter_category_name'),
        ('shop', '0015_banner_approved_at_banner_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='call_to_action_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReactSerializers.item'),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_type',
            field=models.CharField(choices=[('item', 'Item'), ('external', 'External URL')], default='item'),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
