# Generated by Django 4.2.11 on 2026-09-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_career'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at']},
        ),
    ]
