# Generated by Django 5.1.7 on 2025-10-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0002_vendorrequest_brand_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='password',
        ),
    ]
