# Generated by Django 5.1.7 on 2025-11-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0005_returnrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
