# Generated by Django 5.1.7 on 2025-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0010_vendoradjustment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayout',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
