# Generated by Django 5.1.7 on 2025-11-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorDashboard', '0013_vendorpayout_mpesa_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayout',
            name='paypal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='paypal_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='paypal_payout_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='paypal_transaction_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
