# Generated by Django 5.1.7 on 2025-11-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_address_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
