# Generated by Django 6.0.6 on 2026-06-11 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_url_alter_notification_visitor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 7, 11)),
        ),
    ]
